### PR TITLE
.gitignore: add src/unix/uv-dtrace.h

### PR DESCRIPTION
**Pull request by rurban**

### CODE REVIEW

**Comment by bnoordhuis** [comment]
How/why did it end up in src/unix? /cc @tjfontaine

**Comment by tjfontaine** [comment]
On current master I don't see this

```
[tjfontaine@jenkins ~/libuv]$ git status
# On branch master
nothing to commit (working directory clean)
[tjfontaine@jenkins ~/libuv]$ find . -name uv-dtrace.h
./include/uv-dtrace.h
```

When building in tree, and out of tree:

```
make[1]: Leaving directory `/home/tjfontaine/lt'
[tjfontaine@jenkins ~/lt]$ find . -name uv-dtrace.h
[tjfontaine@jenkins ~/lt]$ cd ../libuv
[tjfontaine@jenkins ~/libuv]$ find . -name uv-dtrace.h
./include/uv-dtrace.h
```

**Comment by bnoordhuis** [comment]
Okay, thanks.

@rurban Is the issue repeatable for you with the current HEAD of master?  The generated header is not supposed to end up in src/unix.

**Comment by rurban** [comment]
Indeed. I must have mixed it up with an older checkout.
`GEN include/uv-dtrace.h`
Only this one.

**Pull request closed without merging**
