### PR TITLE
Fix mingw32 build

### PR DESCRIPTION
**Pull request by mattn**
mingw32 doesn't have OnLinkPrefixLength

### CODE REVIEW

**Comment by saghul** [comment]
Does MinGW64 also not have it?

**Comment by mattn** [comment]
It seems OK to me 

https://gitorious.org/w64/w64/source/389d24fb1dc74d849fcf3794989924c39d6c0a18:mingw-w64-headers/include/iptypes.h#L96-105

**Comment by piscisaureus** [comment]
I disagree with this patch; on mingw builds `prefix_len` will simply be never assigned a value, leading to undefined behavior further down. 

This issue isn't caused by mingw not supporting this API; it's simply lacking the right definitions in one of it's header files. Libuv typically carries definitions that certain toolchains might lack; take a look at `src/win/winapi.h`, that's where a solution should go.

**Comment by mattn** [comment]
@piscisaureus Ah, I notice it just now. I'll fix tommorow

**Comment by huxingyi** [comment]
already fixed in https://github.com/joyent/libuv/pull/1555

**Comment by mattn** [comment]
That is in 1.X branch. please backport to master

**Comment by saghul** [comment]
1.x is the stable branch.

**Comment by mattn** [comment]
Yes, I know. When I will be able to build master branch on mingw32 ?

**Comment by saghul** [comment]
I'll merge 1.x into master after the next release. After we changed the
versioning scheme I'd suggest to stick to the 1.x branch. master will
eventually introduce breaking changes without notice, since that's where
new development will happen.

**Pull request closed without merging**
