### PR TITLE
build: add support for Windows SDK

### PR DESCRIPTION
**Pull request by schlamar**
With this patch vcbuild.bat is able to detect if it is run within a Windows SKD Command Prompt. In this case it does not try to configure variables because they are already set.

### CODE REVIEW

**Comment by schlamar** [comment]
As motivation, Windows SDK allows 64bit builds for free.

**Comment by tjfontaine** [comment]
can you try with #1006 instead, and see if relying on gyp's detection will work for you?

**Comment by schlamar** [comment]
Do you mean #1003?

**Comment by schlamar** [comment]
Closing in favor of #1107 and #1108. :)

**Pull request closed without merging**
