### PR TITLE
unix: return UV_EAGAIN if uv_try_write cannot write any data

### PR DESCRIPTION
**Pull request by saghul**
For consistency with `uv_udp_try_send`.

Yes, UDP and TCP are different but I think it reasonable to think users will expect the same behavior on both cases. The reason why we return EAGAIN on UDP is bbecause sending an empty datagram is allowed, so we need to know if what happened is that the datagram could not be sent vs an empty datagram was sent. We cannot send an empty TCP packet, but still IMHO consistent behavior is a Good Thing (TM) in this case.

/cc @indutny

@txdv come and agree with me here :-)

### CODE REVIEW

**Comment by indutny** [comment]
LGTM, but please remind me about it when we'll upgrade libuv in node.

**Comment by saghul** [comment]
Will do!

**Comment by txdv** [comment]
We **need** to do it for UDP, we don't _need_ to do it for TCP.

But I am for this because of consistency.  :+1:

**Comment by saghul** [comment]
That's what I tried to say in the description. Will merge when brain is fully functional.

**Comment by txdv** [comment]
Your description says exactly the same , I just made a shorter conclusion of it.

**Comment by saghul** [comment]
Landed in https://github.com/joyent/libuv/commit/40ad12e5bedb7f328328f5fb634203e3b84b9af9. I also fixed the test so it would actually test the functionality, in https://github.com/joyent/libuv/commit/b018dc5b72452e3db6fbab00ac1f2b71c4747c43. Before the test would also bail out if the return value was 0, which was always the case on OSX. Now we use a small buffer which makes the test pass.

**Comment by saghul** [comment]
@indutny here is the fix for node: https://github.com/joyent/node/pull/7899

**Comment by ibc** [comment]
:cake:

**Pull request closed without merging**
