### PR TITLE
windows: several fixes

### PR DESCRIPTION
**Pull request by maksqwe**

### CODE REVIEW

**Comment by maksqwe** [comment]
I reseted my fork and commit again fixes based on your comments

**Comment by piscisaureus** [comment]
Alright, lgtm. Did you sign the CLA?

**Comment by maksqwe** [comment]
Already signed.
P.S. "Sign Electronically" not shown on Firefox 23-24, IE9 - ok

**Comment by bnoordhuis** [comment]
Thanks Maks, landed in d964b53, 2a87d28 and cd9eadc.

**Comment by bnoordhuis** [comment]
Sorry, make that d170c91, 1ab3e3f and 68795b7.

**Pull request closed without merging**
