### PR TITLE
Fix uv_getaddrinfo to accept custom data.

### PR DESCRIPTION
**Pull request by erickt**
I noticed that the unix backend for `uv_getaddrinfo` is zeroing out the the `uv_getaddrinfo_t` handle, which prevents the user from providing custom data to the callback result. This patch adds a `uv_getaddrinfo_init` that zeros out the data before `uv_getaddrinfo_t` before calling the function.

Edit: I've updated the patches against HEAD, and pulled some of the patches that we need for compiling the [Rust language](http://github.com/graydon/rust).

### CODE REVIEW

**Comment by erickt** [comment]
Added a couple fixes for mingw-w64.

**Comment by japj** [comment]
@erickt it might help to split new features/fixes.

also from looking at#155 it is already included in libuv at 6793b53e626d3f39ad149f8bbbd3f5b8de1708c5 right?

**Comment by erickt** [comment]
@japj, I split up the patch into just the bug fixes. I'll submit a pull request for the makefile changes later. Regarding #155 and commit 6793b53, I can't actually find that commit. Did it accidentally get dropped?

**Comment by ry** [comment]
rather than adding another function, can we just add a `void* data` parameter to `uv_getaddrinfo` ?

**Comment by ry** [comment]
i merged c28c780 063cf1e and 45e7f47

in 1a43429 fe6157b and f4e2d55

**Comment by ry** [comment]
submit new pull for the others.

**Comment by ry** [comment]
also landed 5b567b2

**Pull request closed without merging**
