### PR TITLE
Add UV_PROCESS_WINDOWS_HIDE to avoid consoles on Windows

### PR DESCRIPTION
**Pull request by shanewholloway**
UV_PROCESS_WINDOWS_HIDE enables supression of process windows when launching subprocesses on Windows platforms from a executable linked to the WINDOWS subsystem (as opposed to the CONSOLE subsystem).

### CODE REVIEW

**Comment by piscisaureus** [comment]
I'm fine with this. Can you sign the CLA? http://nodejs.org/cla.html

**Comment by shanewholloway** [comment]
Fantastic!  CLA signed & submitted.

Do I need to port this to the 0.9 branch?

**Comment by piscisaureus** [comment]
Landed (with some style modifications and fixing an assertion on unix) in 5d92ccc.

@shanewholloway PS. you may want to configure your git username, you show up as `"Shane Holloway ext:(%22) <shane.holloway@ieee.org>` here.

**Comment by shanewholloway** [comment]
@piscisaureus thanks for letting me know — it is fixed for the future.

**Comment by txdv** [comment]
Em, one question.
Why didn't you make HIDE the default setting and add a flag which would SHOW it?
Wouldn't it be more consistent behaviour since you can on unix create it in hidden mode?

**Comment by shanewholloway** [comment]
When I was writing it, I was more concerned about not changing any existing behavior — SW_SHOWDEFAULT is the default behavior for Win32's CreateProcess. Making HIDE the default makes great sense based on your argument.

**Pull request closed without merging**
