### PR TITLE
uvgetaddrinfo

### PR DESCRIPTION
**Pull request by HenryRawas**
Here are my getaddrinfo changes

### CODE REVIEW

**Comment by piscisaureus** [comment]
These are the comments I sent by e-mail. Posting them here so we can practice pull request review a bit :-)

---

I reviewed Henry’s getaddrinfo patch and it looks good so far.

Question: should we force the caller to hang on the strings and structs that the addrinfo struct points to? Or would we rather copy them? I know libeio does the latter, I don’t really know what I prefer. Ryan, Igor?

These are just nits:
-   Declare internal stuff as static
-   Maybe initialize the WAKEUP req in uv_getaddrinfo instead of in the thread?
-   It may be worthwhile to use the Unicode version of getaddrinfo instead of the ascii one, and convert the input (which will be utf-8) to UT-16.

\- Bert

**Comment by HenryRawas** [comment]
Using getaddrinfoW would mean parsing the returned data as well to convert any names from UNICODE back to UTF-8.

**Comment by piscisaureus** [comment]
> Using getaddrinfoW would mean parsing the returned data as well to convert any names from UNICODE back to UTF-8.

That's true but the alternative is to not support any non-ascii characters. That's not good, unless there's not any conceivable case where people would need unicode support. (honestly I can't think of any case right now)

**Comment by bnoordhuis** [comment]
@piscisaureus RFC 2181 allows octets > 127 but no browser or resolver I know of actually supports that. DNS in the real world doesn't talk Unicode, it's either ASCII or Punycode (which is ASCII too).

**Comment by piscisaureus** [comment]
Landed in 295fa6f538e7975e44c2c495781c7b0fc308d6b1

**Pull request closed without merging**
