### PR TITLE
build: fix compilation warning if dtrace doesn't work

### PR DESCRIPTION
**Pull request by saghul**
Check if dtrace should instrument object files only if dtrace
support is detected to work

### CODE REVIEW

**Comment by saghul** [comment]
This fixes the build error I'm seeing on FreeBSD 10, where dtrace is present, but configure says it's not working, so don't bother checking if object files should be instrumented.

/cc @indutny @tjfontaine

**Comment by indutny** [comment]
LGTM, but needs @tjfontaine acception too

**Comment by saghul** [comment]
Sure, thanks for having a look Fedor!

**Comment by tjfontaine** [comment]
lgtm

**Comment by saghul** [comment]
Thanks guys, landed.

**Pull request merged**
