### PR TITLE
unix: map `EROFS` to `UV_EROFS`

### PR DESCRIPTION
**Pull request by mmalecki**
No idea how to test it or implement on Windows.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
@piscisaureus: Is `ERROR_FILE_READ_ONLY` the corresponding Windows error code?

**Comment by piscisaureus** [comment]
@bnoordhuis No - ERROR_FILE_READ_ONLY means that the file has the read-only bit set. It should report whatever error you get on unix when the user has no write permission on that file.

Windows has no concept of read-only mounts. Some mounts can be write protected in practice (like, the driver doesn't support it, or you're trying to write to a DVD). That would result in EACCESS on windows.

I think you should map ERROR_WRITE_PROTECT to EROFS though.

**Comment by bnoordhuis** [comment]
Thanks Maciej, merged in 58733d1.

**Comment by piscisaureus** [comment]
Hmm, so no ERROR_WRITE_PROTECT mapping uh?

**Comment by bnoordhuis** [comment]
You haven't been paying attention, have you? :-) See here: d5e7786

**Pull request closed without merging**
