### PR TITLE
stream: fix uv__stream_osx_select

### PR DESCRIPTION
**Pull request by indutny**
Relying on `readable`/`writable` when polling will lead to the select
thread spinning in the loop and calling `uv_async_send()`, because
stream may never become not `readable`/`writable`.

We should rely on `uv__io_active()` instead and interruprt select thread
every time it changes.

/cc @saghul see https://github.com/joyent/node/issues/6733#issuecomment-30916143

### CODE REVIEW

**Comment by saghul** [comment]
How is it possible that it never becomes "readable"? The stream flags are set in `uv__stream_open`, which is called right after `uv__stream_try_select`.

**Comment by indutny** [comment]
It never becomes not "readable", because we're no checking UV__POLLIN presence.

**Comment by saghul** [comment]
Le me rephrase :-) Before we used to check for the intention, no we check if the stream is _actually_ readable or writable. If that is what we really want, then LGTM.

**Comment by indutny** [comment]
Yeah, that's what we really need :) Otherwise it just loops there and sends `async`s to the main thread.

**Comment by saghul** [comment]
I see. Go for it then! :+1:

**Comment by indutny** [comment]
Thank you, landed in 08cafd0

**Pull request closed without merging**
