### PR TITLE
build: fix windows smp build with gyp

### PR DESCRIPTION
**Pull request by geertj**
Gyp will try a parallel build if it detect the system has >1 processor.
This functionality depends on the Python "multiprocessing" package. The
multiprocessing package on Windows requires that the top-level module is
importable as a module, see:

  http://docs.python.org/2/library/multiprocessing.html#windows

This fixes issue #984.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
LGTM if it works.  First line of the commit log should be something like 'build: fix windows smp build with gyp' (50 columns max.)  Other lines should wrap at 72 columns.

**Comment by geertj** [comment]
I tested this patch on Linux and Windows.

I updated the message on the pull request, but any pointers on how to update the commit message of the commit that I already pushed?

Also signed the CLA..

**Comment by saghul** [comment]
LGTM. @geertj you can amend your commit (commit --amend) or do an interactive rebase (rebase -i HEAD~1) and then force push (push -f) to this branch. That should do.

**Comment by geertj** [comment]
@saghul, thanks for the tip. Updated and re-pushed

**Comment by bnoordhuis** [comment]
Cheers Geert, landed in 2445467 and 991409e (master and v0.10.)

**Pull request closed without merging**
