### PR TITLE
windows: translate system errors in uv_spawn

### PR DESCRIPTION
**Pull request by orangemocha**
We weren't translating errors for CreateProcessW.

I also reorganized the code a little to make it easier 
to read.

This is half a fix for node's unit test 
test-child-process-cwd.js on win.
The rest will go into node lib.

It also fixes test-child-process-exec-error

### CODE REVIEW

**Comment by orangemocha** [comment]
Fixed the commit message issue.

**Comment by orangemocha** [comment]
I don't think these test failures our due to my change. Do I need to do anything to make sure this PR is still getting considered? Thanks!

**Comment by indutny** [comment]
@orangemocha Thank you, I'll look into it shortly. So far, main thing that distracts me is that you have two different changes in one commit: fix and refactor. I'd suggest splitting it up into two commits to make thing more visible.

**Comment by orangemocha** [comment]
I split this into two commits as you suggested. Thanks!

**Comment by saghul** [comment]
I left a couple of minor comments. Also, can you please reword your commit message to something like "windows: do this and that in uv_spawn" :-)

**Comment by orangemocha** [comment]
I think all feedback so far has been addressed.

**Comment by saghul** [comment]
Please change the subsystem to "windows", so your commit messages would be: "windows: translate system error in uv_spawn" and similar for the other one.

Otherwise LGTM.

**Comment by orangemocha** [comment]
Thank you for your patience. Still learning all these git jewels :) Should be ready now.

**Comment by saghul** [comment]
No problem @orangemocha :-)

**Comment by saghul** [comment]
Thanks @orangemocha, it landed!

**Pull request merged**
