### PR TITLE
bsd: support IPv6 qualified link-local addresses

### PR DESCRIPTION
**Pull request by saghul**
AFAICT (online man pages) all BSDs we support have `if_nametoindex` in net/if.h, so use it. Tested on FreeBSD 10.

/cc @indutny @bnoordhuis

### CODE REVIEW

**Comment by bnoordhuis** [comment]
LGTM

**Comment by saghul** [comment]
Landed! Thanks Ben!

**Comment by tjfontaine** [comment]
sunos also `if_nametoindex` http://illumos.org/man/3xnet/if_nametoindex

**Comment by saghul** [comment]
Thanks for the heads up, I'll push a fix!0

**Comment by saghul** [comment]
https://github.com/joyent/libuv/pull/1229

**Pull request merged**
