### PR TITLE
Disable crtdbg on MinGW. refs #583

### PR DESCRIPTION
**Pull request by hnakamur**

### CODE REVIEW

**Comment by bnoordhuis** [comment]
LGTM. @piscisaureus?

**Comment by piscisaureus** [comment]
@hnakamur Are you saying it's not necessary on mingw? Or is it just that crtdbg.h is not available?

**Comment by hnakamur** [comment]
The latter. crtdbg.h is not just available on MinGW. I don't know it's not necessary on MinGW.

BTW, I found it in mingw-w64-v2.0.7, but _CrtSetReportMode is defined as no-op macro, not a real implementation.

**Comment by piscisaureus** [comment]
Thanks, landed in 2684f876a

**Pull request closed without merging**
