### PR TITLE
Fix windows build

### PR DESCRIPTION
**Pull request by mattn**
```
cc -Wall -Wextra -Wno-unused-parameter -Iinclude -Isrc -Isrc/win -DWIN32_LEAN_AND_MEAN -D_WIN32_WINNT=0x0600 -c -o src/fs-poll.o src/fs-poll.c
In file included from include/uv.h:59:0,
                 from src/fs-poll.c:22:
include/uv-win.h:475:9: error: duplicate member 'reserved'
   void* reserved;
         ^
include/uv-win.h:482:14: note: in expansion of macro 'uv_pipe_connection_fields'

     struct { uv_pipe_connection_fields };                                     \

              ^
include/uv.h:1225:3: note: in expansion of macro 'UV_PIPE_PRIVATE_FIELDS'
   UV_PIPE_PRIVATE_FIELDS
   ^
Makefile.mingw:84: recipe for target 'src/fs-poll.o' failed
mingw32-make: *** [src/fs-poll.o] Error 1
```

### CODE REVIEW

**Comment by saghul** [comment]
Thanks! Landed in 49cb40c47902dd04c7787e6543e9e13368dc1840.

**Comment by huxingyi** [comment]
Is it ABI compatible to remove a variable which included in uv.h(struct uv_pipe_s) ?

**Comment by saghul** [comment]
> Is it ABI compatible to remove a variable which included in uv.h(struct uv_pipe_s) ?

No, but 1.0.0 has not been released yet.

**Comment by mattn** [comment]
I'm guessing that breaking ABI compatible had done before my commit. Because compile error is `duplicated field name`.

**Pull request closed without merging**
