### PR TITLE
Remove trailing whitespace.

### PR DESCRIPTION
**Pull request by txdv**
These things are annoying if you use an editor configuration like me, which points them out.

### CODE REVIEW

**Comment by indutny** [comment]
May I ask you to take a look at https://github.com/joyent/libuv/blob/master/CONTRIBUTING.md#commit ?

**Comment by indutny** [comment]
Your commit message style is clearly deviating from our current one.

**Comment by txdv** [comment]
style: remove trailing whitespace

Is this what you want to see?

**Comment by indutny** [comment]
Yes :)

**Comment by txdv** [comment]
Here we go.

**Comment by indutny** [comment]
Landed in 36b38cbdba5638bb03be116270fa8282a391ecae, thank you!

**Pull request closed without merging**
