### PR TITLE
Fixed vcbuild.bat.

### PR DESCRIPTION
**Pull request by ghost**
gyp_uv was complaining because it never receives a value for which
type of library to build (static vs shared). Basically just set the
default to build a static library.

Maybe the default should be shared but either one fixes the build.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
LGTM. @piscisaureus?

**Comment by piscisaureus** [comment]
I haven't noticed this problem, but it looks reasonable.

@shancat I know it's a one-liner but can you sign the CLA? http://nodejs.org/cla.html

**Comment by ghost** [comment]
I've already signed the CLA for PRs to the node repo before.

**Comment by piscisaureus** [comment]
@shancat Sorry, I must have overlooked it. Thanks, landed in 8afd71a.

**Pull request closed without merging**
