### PR TITLE
Support android cross compile on mac.

### PR DESCRIPTION
**Pull request by eddyb**
_Upstreaming @yichoi's patch from @rust-lang [libuv](https://github.com/rust-lang/libuv/tree/800b56fe6af21ffd8e56aee8cf12dd758f5bbdf1)._

### CODE REVIEW

**Comment by saghul** [comment]
HAve you tried using these instructions? https://github.com/joyent/libuv#android

**Comment by alexcrichton** [comment]
I tried using those instructions, but they didn't quite work out for me. I ran into numerous problems running the script, but when I got it configured I get make errors such as https://gist.github.com/alexcrichton/9858498.

I'm not entirely sure why gcc isn't being invoked correctly, but it looks like it's attempting to build with `-arch x86_64` even though the `target_arch` to gyp is `arm`. I don't really fully understand gyp though, so I may be doing something wrong!

**Comment by saghul** [comment]
Do you have these binaries in your toolchain? https://github.com/joyent/libuv/blob/master/android-configure#L11-L14

I'll give it a try myself, but it'll take me a bit...

**Comment by alexcrichton** [comment]
I do indeed, I think that gyp may just be passing through the wrong flags, or expecting ARM on OSX to be for iOS rather than android?

**Comment by saghul** [comment]
Note to self: http://stackoverflow.com/questions/22719843/generate-makefileor-android-mk-for-android-ndk-using-gyp-on-os-x

**Comment by xudejian** [comment]
yeah, it's work for me

**Comment by abhinavsingh** [comment]
nvmind, I see attached patch helps me proceed, thanks.

**Comment by saghul** [comment]
@abhinavsingh the attached patch is a bit of a hack. We need a better way to this, alas I couldn't find the time to dig into it. If you have any idea on how to do it properly, that would be great :-)

**Comment by bnoordhuis** [comment]
I think this can be closed as no longer relevant now that rust has dropped libuv?  Or is it applicable outside of cross-compiling rust?

**Comment by abhinavsingh** [comment]
Ben, I encountered this when I was compiling C code (depending upon libuv)
using NDK build system for Android.

**Comment by eddyb** [comment]
Closing old PRs of mine.

**Pull request closed without merging**
