### PR TITLE
unix: optimise UDP buffer allocation

### PR DESCRIPTION
**Pull request by unixwitch**
Instead of always allocating a 64KB buffer, use FIONREAD to check the size of the next incoming packet.

I intended to use FIONREAD here to check if any packet is pending, and avoid allocating a buffer (simply returning instead) if no packet is pending.  However, this isn't possible with FIONREAD: if a zero-byte packet is pending, we would spin forever as the socket will appear readable but we'll never read the packet.

Still, this is a minor worthwhile optimisation.

### CODE REVIEW

**Comment by unixwitch** [comment]
NB: this actually ends up swapping a malloc() for a syscall (ioctl), so perhaps benchmarking would be worthwhile to see which is better.

**Comment by unixwitch** [comment]
With these commits, we now avoid allocating a buffer entirely when there's no packet to be received.

**Comment by saghul** [comment]
IIRC @bnoordhuis had some thoughts on this. Can you comment, Ben?

**Comment by bnoordhuis** [comment]
I've experimented with FIONREAD / SIOCINQ it in the past.  The tl;dr is that the extra system call cuts throughput in half on most platforms (ioctls are expensive) and that it's almost always faster to malloc/realloc.  If you worry about malloc overhead, use some kind of slab allocation scheme.

A separate but related issue is that, on some platforms, the ioctl returns the size of the first pending datagram while on other platforms, it returns the size of all pending datagrams.

**Comment by unixwitch** [comment]
Okay, that makes sense - shame though.

I'm not overly concerned about the speed of modern malloc()s, just thought I'd have a look as someone mentioned this behaviour on IRC.

**Pull request closed without merging**
