### PR TITLE
Added io handle (unix)

### PR DESCRIPTION
**Pull request by saghul**
Added uv handle for monitoring arbitrary file descriptors, it's a thin wrapper around ev_io (sorry, unix only, I don't know how to do it for windows).

This should close issues #288 and #265.

I have a very dirty test which I'll clean and submit as well, but I'd like to receive some initial feedback on the API.

Thanks,

### CODE REVIEW

**Comment by bnoordhuis** [comment]
Thanks, the patch looks good.

Bear with me for now, I can't merge it right away. @piscisaureus and I have been discussing a similar API but we haven't quite made up our minds on how to do the actual I/O: tie in with regular streams, provide read/write functions like your patch does, let the user handle it, etc.

**Comment by saghul** [comment]
Hi,

Sure, I just wanted to get some feedback on the patch, feel free to suggest  changes :-) FWIW, when I was implementing it I was about to just let the suer handle it, but I thought that providing functions would help, at least with errno mapping.

**Comment by ronkorving** [comment]
This is beautiful. I was trying dealing with the same problem, breaking my head on it for days now, and you've provided an answer, saghul. I hope the team will deal with this sooner rather than later. If it makes its way into Node 0.8, I might actually be able to use it :)

**Comment by saghul** [comment]
Hi @ronkorving,

Thanks for the comment :-) Apparently it will be added, but my proposed API might not be the chosen one, though I guess it'll be somewhat similar. Another missing part is the Windows equivalent for this, but I think @piscisaureus said it can be done.

The reason why I need it is because I implemented Python wrappers for libuv (http://github.com/saghul/pyuv) and I'm now building a library on top of that using greenlets. So in order to make Python sockets cooperative I need to run an Io handle on their fileno().

**Comment by ronkorving** [comment]
I'm working on a wrapper module for Couchbase, for which the library is based on an eventloop like libev(ent). So I really need a callback when select() is positive, but before the read(). No need for libuv to gather all read buffers together for me, since libcouchbase already implements that. I need libcouchbase to do the read, whenever the event system tells me there is data available.

**Comment by piscisaureus** [comment]
Binding to external libraries is why we need to support this. However on windows it will not offer the best performance. So @saghul, I think you would be better off finding a different way to deal with it for pyuv.

**Comment by saghul** [comment]
Thanks for the comment, @piscisaureus. My little project is still in diapers, so I can still try to find an alternative :-) Anyhow, other similar projects use select on Windows, do you think this 'Io' handle performance would be worse than select?

**Comment by piscisaureus** [comment]
Well, select() on windows is very bad :-). Our performance might actually be a little better, but not as good as with IOCP.

**Comment by saghul** [comment]
Thanks! That might be good enough to get started with :-)

**Comment by ronkorving** [comment]
"Not as good as with IOCP" is still much better than "impossible to integrate your library, sorry" or circumventing libuv and having to hack into libev directly.

**Comment by graydon** [comment]
If I understand correctly, this is the "emulate readiness using completion" side of the problem uv was designed to solve. If so I think this is probably undesirable. Since uv exists, if I understand correctly, in a large measure to provide the completion (IOCP-style) emulation on readiness interfaces of libev. In other words, if you want readiness and you want to paint yourself into a corner of only working on unix, you ... already have libev. There's no point using libuv. Doesn't buy you anything. Adding code to punch through to libev just breaks the things libuv was made to provide _beyond_ libev.

Maybe I misunderstand.

(Also, `select` is worse than just "slow" on windows. It doesn't actually work with most types of filehandle, and it has a fixed upper limit on the number of sockets it does handle. It's a very poor readiness emulation.)

**Comment by piscisaureus** [comment]
@saghul Why did you add uv_io_read and uv_io_write ?

**Comment by saghul** [comment]
@piscisaureus I thought they could be handy, specially for setting the error in the loop in case something bad  happens. That way the user doesn't need to translate errnos.

**Pull request closed without merging**
