### PR TITLE
change GENERIC_ALL to GENERIC_WRITE in fs__create_junction

### PR DESCRIPTION
**Pull request by tkelman**
fixes https://github.com/joyent/libuv/issues/1385, creating NTFS junctions in directories that are apparently missing certain permissions on Windows.

### CODE REVIEW

**Comment by saghul** [comment]
A quick look shows that this is how ReactOS does it, right?

**Comment by tkelman** [comment]
Yup. See https://github.com/mirror/reactos/blob/c69ae24f90028bf3bdba150885a924080e007117/reactos/base/shell/cmd/mklink.c#L84 - they also don't use `FILE_FLAG_OPEN_REPARSE_POINT`, but in my little test program that didn't make a difference as far as I could tell.

**Comment by saghul** [comment]
I see. Calling the Windows cavalry: @piscisaureus, @orangemocha, can either of you give this a quick look? Looks reasonable to me.

**Comment by saghul** [comment]
FTR: http://stackoverflow.com/a/10508724

**Comment by piscisaureus** [comment]
Changing to GENERIC_WRITE lgtm.

**Comment by saghul** [comment]
Thanks Tony! Landed in https://github.com/joyent/libuv/commit/3d73d5562791e8fe115732decd38db06a199e46a. Also thanks for confirming Bert!

**Comment by tkelman** [comment]
Cheers. Keep up the good work guys. One of these days Julia (and Rust et al) won't need a fork anymore and we'll get everything we need all in the same place.

**Comment by saghul** [comment]
> Cheers. Keep up the good work guys. One of these days Julia (and Rust et al) won't need a fork anymore and we'll get everything we need all in the same place.

Thanks! That's what we aim for.

**Pull request closed without merging**
