### PR TITLE
If `options.env` is not provided, do not replace the child's environ

### PR DESCRIPTION
**Pull request by AvianFlu**
Currently, setting `options.env` to `NULL` for `uv_spawn` results in a child process for whom `environ == NULL`.  This can cause a wide variety of unexpected issues - this patch is a simple fix, and a test for the issue.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
Thanks Charlie, landed in 1d85815.

**Comment by bnoordhuis** [comment]
And in fb64948 in v0.8.

**Comment by piscisaureus** [comment]
You broke the windows build guys. Well done!

**Comment by bnoordhuis** [comment]
Why? setenv?

**Pull request closed without merging**
