### PR TITLE
test: make sure all handles in the loop are closed

### PR DESCRIPTION
**Pull request by saghul**
After https://github.com/joyent/libuv/commit/2611ef43b15dc083ac2ffd5f16901a4ff076be03 hell broke loose because we don't clean up after ourselves in the test suite. I could reproduce the failures in https://github.com/joyent/libuv/issues/1161 when using autoconf but not when using gyp (need to investigate that). Either way, this patch makes sure all handles in the loop are closed before destroying it.

### CODE REVIEW

**Comment by indutny** [comment]
This sounds like a hack. Perhaps, we should find what we are not closing instead?

**Comment by saghul** [comment]
Well, look at test-run-once for example. It's not necessarily wrong to bail early from uv_run if you unref all handles. MAKE_VALGRIND_HAPPY was only added, well, to make valgrind happy, it's not needed, but since we are here we can also make saghul happy ;-)

**Comment by saghul** [comment]
Not to mention that MAKE_VALGRIND_HAPPY is the last thing we do in all tests, so all asserts have already been checked and you know the test passed.

**Comment by indutny** [comment]
Ok, I guess those are not serious problems anyway. LGTM

**Comment by saghul** [comment]
On 02/28/2014 09:53 AM, Fedor Indutny wrote:

> Ok, I guess those are not serious problems anyway. LGTM

Yep, they are not :-) Thanks, Fedor.

## 

Saúl Ibarra Corretgé
bettercallsaghul.com

**Pull request merged**
