### PR TITLE
build: Update build.mk

### PR DESCRIPTION
**Pull request by staticfloat**
Clean `make test` build objects properly.  I ran into this when packaging `libuv` on debian, as when packaging it is important to be able to clean and return to a pristine state.

### CODE REVIEW

**Comment by staticfloat** [comment]
Not sure what subsystem to file this under..... is there a `build:` subsystem?

**Comment by indutny** [comment]
Yes, prefixing it with `build:` should work.

**Comment by staticfloat** [comment]
Done.

**Comment by bnoordhuis** [comment]
Landed in d67d713, thanks.

**Pull request closed without merging**
