### PR TITLE
Implement uid/gid argument to uv_spawn

### PR DESCRIPTION
**Pull request by isaacs**
This is necessary to replace the uid/gid arguments to child_process.spawn in Node, which apparently started silently not working as of 0.6.

### CODE REVIEW

**Comment by tjfontaine** [comment]
I believe uid_t is generally uint32 on linux, it may not be wise to use int to describe uid/gid

**Comment by piscisaureus** [comment]
gid_t is a type, right?

**Comment by piscisaureus** [comment]
als, this could be backported to 0.6 as `uv_spawn2`, similar to what we did for 64 bit file offsets.

**Comment by tjfontaine** [comment]
uid_t and gid_t are types yes

**Comment by isaacs** [comment]
Updated to use uid_t and gid_t.  It's still using -1 as the sentinel value, so if you have a user with a uid of 0xffffffff or whatever, you won't be able to setuid to them, which seems rare and strange enough to not care about.

**Pull request closed without merging**
