### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by saghul**
This PR contains the documentation I've been working on at https://github.com/libuv/api-docs

In order to avoid comment rot (which already happened) I cleaned up uv.h. The API documentation already contains everything uv.h had plus more.

I don't expect anyone to go and prof read it :-) It's not perfect but all API calls are documented, unless I inadvertently missed something. So, trust me on this one and lets keep improving these as we go along.

### CODE REVIEW

**Comment by saghul** [comment]
I forgot to mention, the docs are already available only for viewing here: http://docs.libuv.org It's the same code that is getting merged.

**Comment by saghul** [comment]
/cc @bnoordhuis @piscisaureus @indutny anyone?

"TLDR, LGTM" is also a valid answer :-)

**Comment by bnoordhuis** [comment]
I demand that you do it again but this time in TeX!

I noticed that all the files have trailing newlines.  Is that just coincidence or is there a reason for that?

LGTM BTW. :-)

**Comment by txdv** [comment]
wtf? https://github.com/saghul/libuv/blob/999e17ae96844763ecb163da1879d69eedc21815/docs/src/static/diagrams.key/Data/110809_FamilyChineseOahu_EN_00317_2040x1360-small-12.jpg

**Comment by saghul** [comment]
> I demand that you do it again but this time in TeX!

Just do `make latex`!

> I noticed that all the files have trailing newlines. Is that just coincidence or is there a reason for that?

Personal preference, nothing special :-)

> LGTM BTW. :-)

Awesome, thanks!

**Comment by saghul** [comment]
> wtf? https://github.com/saghul/libuv/blob/999e17ae96844763ecb163da1879d69eedc21815/docs/src/static/diagrams.key/Data/110809_FamilyChineseOahu_EN_00317_2040x1360-small-12.jpg

Hah, that's part of the included Keynotes file with the diagrams. I'm sure Apple has a funny reason to incldue that :-)

**Comment by txdv** [comment]
Remove the not used files. Either show that chinese family on the front page of the docs or just delete it.

**Comment by saghul** [comment]
They are internal to Keynote generated files. I'll try to delete them and
see if it still works OK.

**Comment by saghul** [comment]
Removed unused files. Keynote pops up a warning, but that's all.

**Comment by txdv** [comment]
What is Keynote?

**Comment by saghul** [comment]
http://en.wikipedia.org/wiki/Keynote_%28presentation_software%29

**Comment by saghul** [comment]
Here we go, landed!

**Comment by piscisaureus** [comment]
I'm late to the game - thanks for working on docs.
This is all mambo jumbo to me, so you're now on the hook for reviewing doc PRs till the end if days (insert evil laugh here),

**Comment by saghul** [comment]
Haha, I can give you a crash course any time :-P

**Pull request merged**
