### PR TITLE
FreeBSD: Fix FreeBSD build.

### PR DESCRIPTION
**Pull request by okuoku**
Fix FreeBSD 8.x/9.0 build.

Still fails 3 tests. I'll look into it later..
- Fatal error in test/test-tcp-close.c on line 151: never_cb should never be called
- Assertion failed in test/test-udp-ipv6.c on line 142: recv_cb_called == 1
- Assertion failed in test/test-pipe-bind-error.c on line 56: r == -1

### CODE REVIEW

**Comment by bnoordhuis** [comment]
Right - that's Darwin code, not FreeBSD code.

I'll merge it but can you sign [the CLA](http://nodejs.org/cla.html)?

**Comment by bnoordhuis** [comment]
PS: `test-pipe-bind-error` and `test-tcp-close` are known broken (not specific to FreeBSD).

`test-udp-ipv6` fails because the dual-stack UDP server doesn't receive datagrams from the IPv4 client.

**Comment by okuoku** [comment]
I did.

**Comment by okuoku** [comment]
Yup, tapped wrong place.. sorry.

**Comment by bnoordhuis** [comment]
Thanks, much appreciated. Merged in d1016de.

**Pull request closed without merging**
