### PR TITLE
windows: fix handling closed socket while poll handle is closing

### LINKED ISSUE #1278: Assertion failed: ((handle)->flags & UV__HANDLE_CLOSING) == 0
I'm having this issue with the [libcurl bindings for node](https://github.com/JCMais/node-libcurl) that I'm working on. The same issue is reproducible using the [code present on the uvbook](https://github.com/nikhilm/uvbook/blob/master/code/uvwget/main.c).

It happens only on Windows, the issue is that, when a connection timeout, libcurl try to create a new connection to the next ip, however it fails with the given assertion error.

Example of output:

```
>node examples\simple-request.js www.google.com:81
* Rebuilt URL to: www.google.com:81/
* Hostname was NOT found in DNS cache
*�� Trying 200.149.119.118...
Action: 2
Socket: 00000000
* After 2390ms connect time, move on!
* connect to 200.149.119.118 port 81 failed: Timed out
*�� Trying 200.149.119.89...
Action: 4
Socket: 006A0898
Action: 2
Socket: 00000000
Assertion failed: ((handle)->flags & UV__HANDLE_CLOSING) == 0, file src\win\poll.c, line 190 
```

From what I can see from the curl source code, the connection socket is closed (https://github.com/bagder/curl/blob/master/lib/connect.c#L584), and the socket callback is called (https://github.com/bagder/curl/blob/master/lib/connect.c#L1245 and https://github.com/bagder/curl/blob/master/lib/multi.c#L2092), however when the next connection is made, libuv tries to use a handler that was closed before. (because of the given socket callback being called).

I don't know how the handler is, somewhat, being reused, because the socket callback is called correctly (you can check that on the ouput above, Action 2 means register the uv_handle and 4 means destroy it), and it does close the handler, check: https://github.com/JCMais/node-libcurl/blob/develop/src/Curl.cc#L447.

Anyway, I don't know if this is a bug on libuv, libcurl, on with my code, probably the last one.

### PR DESCRIPTION
**Pull request by saghul**
fixes #1278

### CODE REVIEW

**Comment by indutny** [comment]
Test?

**Comment by saghul** [comment]
I think I can write one, if my assumption about the problem actually stands. Will write one sson.

**Comment by JCMais** [comment]
@saghul Any updates? (:

**Comment by saghul** [comment]
I still need to write a test for this, but I'm a bit busy these days. Can you help with that?

**Comment by JCMais** [comment]
I was just pinging, since it's common to forget when you have many issues to take care.

I can help, but if it's to write it, you are probably going to have more work if I do so, since I don't know where to start (4 weeks of experience with C/C++). =P

**Comment by saghul** [comment]
No worries. I hope I find time for writing it next week.

**Comment by saghul** [comment]
Added test. Can you PTAL, @indutny?

**Comment by indutny** [comment]
LGTM, thank you!

**Comment by sequoiar** [comment]
can back port to v0.8 ?

**Comment by saghul** [comment]
To 0.10 yes, but I believe 0.8 is EOLd. Nevertheless, the patch should apply cleanly.

**Comment by saghul** [comment]
Thanks Fedor, landed!

**Comment by mscdex** [comment]
@saghul Any love for v0.10?

**Comment by saghul** [comment]
Thanks for the reminder! Will do in a few days!

**Comment by saghul** [comment]
Here goes the love: https://github.com/joyent/libuv/commit/12bb46c095032b5106ffbd6feb1931917dcdd9d9 :sparkling_heart:

**Comment by mscdex** [comment]
:thumbsup:

**Pull request merged**
