### PR TITLE
doc: clarify the return value of uv_default_loop(void) function in uv.h.

### PR DESCRIPTION
**Pull request by ghmlee**
When I called the uv_default_loop(void) fucntion in my main function, I was confused about should I call the uv_loop_init(uv_loop_t\* loop) function or not.

So, I added a comment that is "Returns the `initialized` default loop".

### CODE REVIEW

**Comment by indutny** [comment]
Btw, @saghul : this function may return `NULL` because of the allocation failure, should we assert internally? Or just document it?

**Comment by indutny** [comment]
LGTM

**Comment by saghul** [comment]
> Btw, @saghul : this function may return NULL because of the allocation failure, should we assert internally? Or just document it?

I'd go for documenting it. Can you also add a "NOTE:" about that as well @ghmlee?

**Comment by ghmlee** [comment]
@saghul @indutny I wrote a new commit. Also, this is new pull request.
https://github.com/joyent/libuv/pull/1367

**Comment by saghul** [comment]
Closing this one then. New time, @ghmlee you can just force push into the same branch and reuse the same PR :-)

**Pull request closed without merging**
