### PR TITLE
test: allow UV_EACCES in spawn_fails (#1045)

### PR DESCRIPTION
**Pull request by jneu**
Addresses issue #1045.

Allow UV_EACCES as a successful return value when uv_spawn fails.
When the PATH environment variable contains a directory which the
user cannot access, execvp may return EACCES instead of ENOENT.

### CODE REVIEW

**Comment by saghul** [comment]
Any way EACCES can be simulated in the test case?

**Comment by jneu** [comment]
I don't think we can reliably. It's OS dependent on when `execvp` will return ENOENT or EACCES.

For example, on my linux system (glibc 2.5), `execvp` will return EACCES if any of the `execve` calls it makes on PATH elements return it. For reference, take a look at the `got_eacces` variable in the glibc source code here:
https://sourceware.org/git/?p=glibc.git;a=blob;f=posix/execvpe.c;h=588e7a71b1a5b507c7628b4ec7a467f4ba78b1d3;hb=HEAD

When testing with my Mac OS X 10.9 system, it appears `execvp` will only return EACCES when `execve` returns EACCES on the _last_ PATH element. The man page is particularly unhelpful:
https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/execvp.3.html
Reference the line containing: "... although only the critical error EACCES is really ambiguous ...".

**Comment by saghul** [comment]
Thoughts, @indutny?

**Comment by indutny** [comment]
Have no objections to it. LGTM.

**Comment by indutny** [comment]
Thank you, landed in b44edf3

**Pull request closed without merging**
