### PR TITLE
osx: Fix a possible segfault in uv__io_poll

### PR DESCRIPTION
**Pull request by alexcrichton**
In our build infrastructure, I've seen a lot of segfaults recently that
were all only happening on OSX. Upon inspecting the coredumps, it
appearded that all segfaults happened at the same instruction, and upon
translating the assembly back to the source, I found that an array could
be indexed with a -1 index before the index was checked to be not -1.

As concrete evidence, here is the situation that I found caused the
segfault.  The instruction in question along with the relevant register
values was:

```
mov    (%r8,%r15,8),%r12

r8  = 0x7fb0ba800000
r15 = 0xffffffffffffffff

r8 + r15 * 8 == 0x7fb0ba7ffff8
```

It appears that the base of loop->watchers was page aligned, and by
going back one word I guess that the page wasn't mapped, causing our
segfaults.

### CODE REVIEW

**Comment by txdv** [comment]
in other words, -1 index access on an array

**Comment by indutny** [comment]
Thank you, LGTM!

**Comment by indutny** [comment]
Landed in f166d6d and f6422af

**Comment by stakach** [comment]
@alexcrichton good catch! I was having this issue too, all tests in that particular project now run without segfaulting. Thanks!

**Pull request closed without merging**
