### PR TITLE
build: adds support for VS2013.

### PR DESCRIPTION
**Pull request by rioki**

### CODE REVIEW

**Comment by saghul** [comment]
Related: https://github.com/joyent/libuv/pull/1012 https://github.com/joyent/libuv/pull/1006 https://github.com/joyent/libuv/pull/1003

IIRC the plan is to get rid of the VS version detection completely.

/cc @piscisaureus

**Comment by saghul** [comment]
@piscisaureus can this be merged until we figure out if we can completely get rid of version detection?

**Comment by tjfontaine** [comment]
@saghul I will spend some time with the build refactory today, but removing all detection should be pretty straight forward, we'll get either @piscisaureus or @sblom for confirmation

**Comment by saghul** [comment]
Great, thanks for confirming @tjfontaine

**Comment by piscisaureus** [comment]
@saghul I don't have 2013 either, but this looks "safe and obvious" so you're welcome to land it.

**Comment by saghul** [comment]
Ok, I'll land it tomorrow if @tjfontaine hasn't found the magic solution thing :-)

**Comment by rioki** [comment]
Sounds good, but unless the changes in GYP are made to use msbuild instead of devenv, the actual build should still be a call to msbuild, like the current version.

**Comment by saghul** [comment]
Thanks @rioki landed as https://github.com/joyent/libuv/commit/a762934aa8c0947ed4d4e1dcbceaeaeb7e765329

**Pull request closed without merging**
