### PR TITLE
speed up net write if socket buffer large enough

### PR DESCRIPTION
**Pull request by freedaxin**
add uv_try_write() to libuv, try to write as many bytes as possible
into socket buffer for nonblocking socket, if all data is written
successfully, async uv write can be avoid, thereby saving the
consumption of uv context and queue operations.

I've opened an issue in node, where explained the reason in detail:
https://github.com/joyent/node/issues/4699

And the corresponding patch for node:
https://github.com/freedaxin/node/commit/d0718d00a231a69c78862bfadab0c7b7b5c59122

### CODE REVIEW

**Comment by saghul** [comment]
This looks similar to what you were tying recently @indutny, maybe we can close this since it wasn't so helpful after all?

**Comment by indutny** [comment]
Well, it won't work at windows, so I decided that it isn't worth having it. Anyway, @freedaxin I wonder how much improvement did it gave to you?

**Comment by freedaxin** [comment]
@indutny, I got a improvement about 30% in my project. Maybe the patch is not perfect, but the approach is right. I wonder what's your "tying recently"?

**Comment by indutny** [comment]
https://github.com/joyent/libuv/pull/1028 , but it doesn't and won't work on windows :)

**Pull request closed without merging**
