### PR TITLE
backport android build for v0.8

### PR DESCRIPTION
**Pull request by sequoiar**
backport libuv master branch of android build to v0.8 branch

### CODE REVIEW

**Comment by saghul** [comment]
0.8 is EOLd AFAICT. This is a new feature, so even if we would still provide security fixes, we won't add this to 0.8 at this stage.

/cc @indutny

**Comment by indutny** [comment]
@saghul I don't really like supporting v0.8 and backporting large code chunks to it. However, I should admit that strictly speaking this is not a new feature, it is just a new platform.

cc @tjfontaine

**Comment by saghul** [comment]
@indutny well given that Android wasn't supported on v0.8 I consider it a new "feature", so I'm personally -1 on this.

**Comment by saghul** [comment]
Nobody vouched strongly for this, so closing.

**Pull request closed without merging**
