### PR TITLE
build: update dtrace m4 check for sunos

### PR DESCRIPTION
**Pull request by tjfontaine**
The check to see if -G is needed for dtrace requires a bit more effort,
make a header, c file, and object file.

### CODE REVIEW

**Comment by saghul** [comment]
I don't have a SunOS to test on, so if it works, LGTM.

**Comment by indutny** [comment]
@tjfontaine why -G could not be needed?

**Comment by tjfontaine** [comment]
@indutny -G is needed on platforms that post-process object files, compared to OSX's implementation where the ASM logic is in the generated header

**Comment by indutny** [comment]
Ok, LGTM

**Comment by tjfontaine** [comment]
Thanks landed in 3310ff4

**Pull request closed without merging**
