### PR TITLE
unix: define NI_MAXHOST and NI_MAXSERV if needed

### PR DESCRIPTION
**Pull request by saghul**
OSX only exposes them if _POSIX_C_SOURCE is not defined, for instance.

### CODE REVIEW

**Comment by indutny** [comment]
Hm... Are you sure that this couldn't be solved by adding proper defines in some places?

**Comment by saghul** [comment]
Not that I know of. Quite the opposite, if some application using libuv
defines _POSIX_C_SOURCE  then OSX doesn't define it.

**Comment by indutny** [comment]
Hm... but how are they propagated to the compiled `.c` files?

**Comment by saghul** [comment]
Not sure what you mean there. I defined it in our Unix internal include, so
all Unix files get it.

You can test it by trying to compile Node with latest libuv on OSX.

**Comment by indutny** [comment]
Aaaah, it is used in headers.... Ok, LGTM

**Comment by saghul** [comment]
Landed!

**Pull request merged**
