### PR TITLE
win: map ERROR_PRIVILEGE_NOT_HELD to UV_EPERM

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by saghul** [comment]
Can you check, @piscisaureus? Thanks!

**Comment by piscisaureus** [comment]
I would say it should map to EPERM and not EACCESS. The reason that symlink fails is not that the user has no write access to this particular file; rather, the process is lacking privileges to create symlinks at all.

**Comment by saghul** [comment]
I doubted between the two and picked EACCES, I can update the pr making it map to EPERM if that's more appropriate.

**Comment by saghul** [comment]
Updated the commit, now it maps to EPERM. 

Btw, I force pushed to update previous commit, is that the right thing to do for pull requests? Thanks!

**Comment by bnoordhuis** [comment]
Thanks, landed in 431d61a. Force-pushing is the right thing to do, yes. :-)

**Pull request closed without merging**
