### PR TITLE
Solaris directory watching resource leak / segfault bug fix

### PR DESCRIPTION
**Pull request by ashaffer**
Libuv doesn't properly clean up directory watches on solaris if they are in the PORT_LOADED state.  I encountered this problem in node.js.  To reproduce it, execute the following in a node console on solaris:

```
fs = require('fs');
h = fs.watch(<directory>);
h.close();
```

Then in a separate shell (without closing the node shell, of course) touch the folder you watched and you should get a seg fault.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
The change itself LGTM but would it be possible to add a regression test?

**Comment by ashaffer** [comment]
Added.

**Comment by bnoordhuis** [comment]
Thanks. Can you sign [the CLA](http://nodejs.org/cla.html)? I believe you're not on the list yet.

**Comment by ashaffer** [comment]
Ok, signed.

**Comment by bnoordhuis** [comment]
Thanks Andrew, landed in 4997738. It'll be part of the next v0.8 node release.

**Pull request closed without merging**
