### PR TITLE
windows: fix mingw32 cross-compilation

### PR DESCRIPTION
**Pull request by bnoordhuis**
@piscisaureus LGTY?

### CODE REVIEW

**Comment by piscisaureus** [comment]
ntdef.h is not available for normal msvc users. Is there no other way?

**Comment by luislavena** [comment]
@piscisaureus @bnoordhuis I think the issue is coming from `winapi.h` NTDEF checks and that it clashes with `uv-win.h` mentioned in #381:

https://github.com/joyent/libuv/blob/master/src/win/winapi.h#L28-34
https://github.com/joyent/libuv/blob/master/include/uv-private/uv-win.h#L131-134

Both are defining it, but none is defining `_NTDEF_` to avoid it being defined again.

Isn't the one in `winapi.h` redundant since `uv-win.h` will be included before?

**Comment by bnoordhuis** [comment]
Sounds plausible. The core issue is that mingw is complaining that NTSTATUS and PNTSTATUS are being redefined (see below). A quick grep suggests that they're defined in ntdef.h, ntsecapi.h and subauth.h. Each file has #ifdef guards in place to prevent redefinition.

```
$ make test MSVC=1 AR=i586-mingw32msvc-ar CC=i586-mingw32msvc-gcc
i586-mingw32msvc-gcc -Iinclude -Iinclude/uv-private -g --std=gnu89 -D_WIN32_WINNT=0x0600 -Isrc/ares/config_win32 -o src/win/async.o -c src/win/async.c
In file included from src/win/internal.h:29,
                 from src/win/async.c:25:
src/win/winapi.h:32: error: redefinition of typedef ‘NTSTATUS’
include/uv-private/uv-win.h:132: note: previous declaration of ‘NTSTATUS’ was here
src/win/winapi.h:33: error: redefinition of typedef ‘PNTSTATUS’
include/uv-private/uv-win.h:133: note: previous declaration of ‘PNTSTATUS’ was here
make: *** [src/win/async.o] Error 1
```

**Comment by luislavena** [comment]
> A quick grep suggests that they're defined in ntdef.h, ntsecapi.h and subauth.h.

Problem is that those headers might not be available on Windows native under some circumstances, mostly will require you install the Platform SDK with is an extra download.

I think that is why it was defined in `uv-win-h` first.

As I commented before, removing the definition from `winapi.h` seems to solve _that_ issue:

```
ubuntu@ubuntu64:~/projects/oss/joyent/libuv$ make test MSVC=1 PREFIX=i586-mingw32msvc-
i586-mingw32msvc-gcc -Iinclude -Iinclude/uv-private -g --std=gnu89 -D_WIN32_WINNT=0x0600 -Isrc/ares/config_win32 -o src/win/async.o -c src/win/async.c
i586-mingw32msvc-gcc -Iinclude -Iinclude/uv-private -g --std=gnu89 -D_WIN32_WINNT=0x0600 -Isrc/ares/config_win32 -o src/win/cares.o -c src/win/cares.c
i586-mingw32msvc-gcc -Iinclude -Iinclude/uv-private -g --std=gnu89 -D_WIN32_WINNT=0x0600 -Isrc/ares/config_win32 -o src/win/core.o -c src/win/core.c
...
```

``` diff
diff --git a/src/win/winapi.h b/src/win/winapi.h
index 4b1a249..ebc53b4 100644
--- a/src/win/winapi.h
+++ b/src/win/winapi.h
@@ -25,14 +25,6 @@
 #include <windows.h>


-/*
- * Ntdll headers
- */
-#ifndef _NTDEF_
-  typedef LONG NTSTATUS;
-  typedef NTSTATUS *PNTSTATUS;
-#endif
-
 #ifndef STATUS_SEVERITY_SUCCESS
 # define STATUS_SEVERITY_SUCCESS 0x0
 #endif
```

**Comment by bnoordhuis** [comment]
@piscisaureus See @luislavena's comment, why are those typedefs in winapi.h?

**Comment by luislavena** [comment]
@piscisaureus ping?

**Pull request closed without merging**
