### PR TITLE
linux: handle O_NONBLOCK != SOCK_NONBLOCK case

### LINKED ISSUE #1442: Handle case when O_NONBLOCK != SOCK_NONBLOCK
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=759673

### PR DESCRIPTION
**Pull request by lucab**
linux-syscalls.h assumes that on all Linux platforms the value
of O_NONBLOCK is the same as SOCK_NONBLOCK.
This commit fixes it, as it is at least not true for hppa, and
resolves #1442.

Signed-off-by: Luca Bruno lucab@debian.org

### CODE REVIEW

**Comment by bnoordhuis** [comment]
Landed in v0.10 in libuv/libuv@5672bbd.  I'll leave the PR open.

**Comment by saghul** [comment]
@bnoordhuis why leave it open?

**Comment by bnoordhuis** [comment]
Because I can't close it.  I'm not a committer (on joyent/libuv) anymore.

**Comment by saghul** [comment]
> Because I can't close it. I'm not a committer (on joyent/libuv) anymore.

Oh, that. Well, it's closed now!

**Pull request closed without merging**
