### PR TITLE
fsevents: FSEvents is most likely not thread-safe

### PR DESCRIPTION
**Pull request by indutny**
Perform all operation with FSEventStream in the same thread, where it'll
be used.

/cc @bnoordhuis @piscisaureus

see https://github.com/joyent/node/issues/6040

### CODE REVIEW

**Comment by indutny** [comment]
Wrong issue number?

**Comment by bnoordhuis** [comment]
LGTM

**Comment by indutny** [comment]
Thanks, landed in 303ae3b.

**Pull request closed without merging**
