### PR TITLE
Add uv_device_t as stream on windows try to handle device io

### PR DESCRIPTION
**Pull request by zhaozg**
Please help me to check right or wrong.

### CODE REVIEW

**Comment by txdv** [comment]
Why are there commits by other people which are already in the mainline?

Open up a pull request against 1.x, not against master

**Comment by zhaozg** [comment]
Some mistake

**Comment by saghul** [comment]
If you plan on working on a big feature like this I suggest you comment on the rationale. Also, I can already see someone asking for baud rates and such, for serial devices. I'm not sure we want to have any of that in libuv.

**Comment by zhaozg** [comment]
I will make a new pr,and with more comments

**Pull request closed without merging**
