### PR TITLE
 build libuv.a and libuv.so in different directories fix #659

### LINKED ISSUE #659: build: build libuv.a and libuv.so in different directories
See e.g. #632.

Running `make all && make test` fails to build the test suite.

`make all` first builds libuv.a, `make test` then tries to build libuv.so but dies with relocation errors.

Possible solutions:
1. Always build with -fPIC. Bad but easy.
2. Build libuv.a and libuv.so in different directories. Good but hard(er).

### PR DESCRIPTION
**Pull request by vtudose**

### CODE REVIEW

**Comment by bnoordhuis** [comment]
Build output should go in out/ (build/ is used by gyp) but apart from that LGTM, thanks! Vlad, can you sign [the CLA](http://nodejs.org/cla.html)?

**Comment by vtudose** [comment]
I've signed the CLA.
I changed the folder to out/
I also modified the targets to take into account the .h files

**Comment by shigeki** [comment]
@vtudose Awesome!  #632 is also resolved. I've never think of MAKECMDGOALS . Thanks.

**Comment by bnoordhuis** [comment]
Thanks Vlad, landed in 4b115f8.

**Pull request closed without merging**
