### PR TITLE
Don't allow NULL callback on timers

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by saghul** [comment]
Quick review @indutny? Also @trevnorris, since discussing with him on IRC lead to discovering this.

**Comment by trevnorris** [comment]
Not sure about the windows timer simplification (e.g. why was it was so complicated before, and why you could simplify it so much). I can spin up my win vm and test it, but I'm sure you've already done that.

Not being allowed to pass `NULL` to `uv_timer_start()` LGTM.

**Comment by saghul** [comment]
> Not sure about the windows timer simplification (e.g. why was it was so complicated before, and why you could simplify it so much). I can spin up my win vm and test it, but I'm sure you've already done that.

Basically the code removed is already tesed for in the functions we call now, that's why I could simplify.

**Comment by trevnorris** [comment]
Awesome. Then LGTM.

**Comment by txdv** [comment]
I feel like the first commit message could have a better description.

**Comment by saghul** [comment]
> I feel like the first commit message could have a better description.

What do you suggest? I didn't really think about it much since it doesn't change functionality. How about "windows: remove duplicated code in uv_timer_again"?

**Comment by saghul** [comment]
Updated commit message, @txdv.

**Comment by txdv** [comment]
well done

**Comment by saghul** [comment]
Thanks for double-checking! Landed on v1.x.

**Pull request merged**
