### PR TITLE
readme/build: fix gyp clone url.

### PR DESCRIPTION
**Pull request by odeke-em**
Cloning gyp via https://git.chromium.org/external/gyp.git
throws a connection failed error. Switching to:
  `git clone https://chromium.googlesource.com/external/gyp.git`
   OR
  `svn co http://gyp.googlecode.com/svn/trunk build/gyp`
works.
This addresses issue #1547

### CODE REVIEW

**Comment by saghul** [comment]
Cheers Emmanuel! Landed in b174a84 (v1.x branch)

**Comment by odeke-em** [comment]
Thanks for merging it in!

**Comment by saghul** [comment]
Thanks for taking the time to contribute! <3

**Comment by acornejo** [comment]
@saghul this still leaves the issue that the generated gyp xcode project does not have an "install" target as referenced in #1545

**Pull request closed without merging**
