### PR TITLE
build: enable all compiler warnings

### PR DESCRIPTION
**Pull request by bnoordhuis**
Currently generates 315 warnings when building `make libuv.la` with gcc 4.8.

Jenkins, I beseech thee.

### CODE REVIEW

**Comment by indutny** [comment]
@bnoordhuis sorry for a delay! I suspect that gyp counterpart is needed as well, isn't it?

**Comment by indutny** [comment]
Though, this commit is LGTM

**Comment by bnoordhuis** [comment]
I don't think there is a good way to check if the compiler supports a particular flag with gyp.

**Comment by indutny** [comment]
Ok, whatever f75bb7c

**Comment by indutny** [comment]
Thanks

**Comment by saghul** [comment]
@indutny IMHO we need to look into the warnings before landing this. As of right now, this is what happens: https://gist.github.com/saghul/9993473

I suggest we revert it for now, fix the problems and land it afterwards.

**Comment by indutny** [comment]
Ok, pushed revert.

**Comment by saghul** [comment]
Thanks Fedor!

**Pull request closed without merging**
