### PR TITLE
Add support for Dragonfly BSD.

### PR DESCRIPTION
**Pull request by jedisct1**
This adds support for Dragonfly BSD.

Tested on i386 and amd64.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
Hey Frank, thanks for this but I'm not sure if I can pull it in. We can't maintain it and, frankly, I have yet to meet my first DragonFly BSD user.

**Comment by ry** [comment]
How much overlap is there with freebsd? Can't they somehow share some of this? I'm not against merging it...

**Comment by jedisct1** [comment]
Hi Ryan,

This is an alternative. See: https://github.com/jedisct1/libuv/commit/fda7ea4da7c39e33bd16c816a765d601a6075c27

**Comment by ry** [comment]
LGTM

**Comment by jedisct1** [comment]
Ok, I'm going to submit another PR for that branch.

**Comment by ry** [comment]
#248

**Pull request closed without merging**
