### PR TITLE
doc: add documentation to to uv_udp_start_recv

### PR DESCRIPTION
**Pull request by txdv**
This clarifies the behaviour of uv_udp_recv_start.

### CODE REVIEW

**Comment by saghul** [comment]
Thanks! This is not entirely correct, here is when nread==0 and addr==NULL can happen: https://github.com/joyent/libuv/blob/master/src/unix/udp.c#L219 As you can see, it's not related to closing the handle. In UDP, since we read datagrams, when the fd is readable we read until we get EAGAIN, but because alloc_cb was called to allocate the buffer for a datagram, we need to return it back, so the recv callback is called with nread==0 and addr==NULL.

**Comment by txdv** [comment]
Why does it call alloc_cb if there is nothing to read?

**Comment by saghul** [comment]
Because we don't know what there is nothing to read. Once the socket is readable we read until we get EAGAIN, but each time re call recvmsg we need to allocate a buffer first. So, when we get EAGAIN we already called alloc_cb and thus we need to give it back to the user in order for him to free the memory.

**Comment by txdv** [comment]
Makes sense.

**Comment by saghul** [comment]
LGTM now. Can you update the patch title? (to to).

**Comment by saghul** [comment]
Thanks a lot Andrius! Landed! :+1:

**Pull request merged**
