### PR TITLE
enable to configure with older versions of autoconf

### PR DESCRIPTION
**Pull request by nori0428**
https://github.com/joyent/libuv/issues/1158
(already closed)

configure.ac at master: AC_PREREQ(2.57)
This means that libuv is enable to configure with autoconf version 2.57 or newer.

But AS_CASE is enable to use autoconf 2.60 or newer version.And AS_CASE has a BUG until version 2.69.
So AC_PREREQ(2.69) might be more better solution.

If you can support older versions of autoconf, please check this patch.
Regards and great thanks for your very useful software.

### CODE REVIEW

**Comment by saghul** [comment]
Thanks @nori0428! I'll give it a shot on OSX 10.6, where autoconf is borked.

**Comment by nori0428** [comment]
I'm sorry. I forgot to write LICENCE.
An attached as_case.m4 file is a part of /usr/local/share/autoconf/m4sugar/m4sh.m4.
'Copyright (C) 2000-2012 Free Software Foundation, Inc.'

**Comment by saghul** [comment]
Hi @nori0428, I tested your patch with autoconf 2.63 (version that shipped with OSX 10.6) and it's working great!

Can you please sign the CLA (http://nodejs.org/cla.html) so I can merge your changes? Thanks!

**Comment by indutny** [comment]
@nori0428 ping ;)

**Comment by saghul** [comment]
Checked the CLA, it's signed. Landed in https://github.com/joyent/libuv/commit/1759781c909cad86ea5387d3c4fa2c87b99a5d55 Thanks!

**Pull request closed without merging**
