### PR TITLE
Add interval and count to keep-alive

### PR DESCRIPTION
**Pull request by jameshartig**
We should be able to specify the probe interval and the failure count for keep-alive's on sockets.

Corresponding node pull request: https://github.com/joyent/node/pull/2239

### CODE REVIEW

**Comment by piscisaureus** [comment]
> We should be able to specify the probe interval and the failure count for keep-alive's on sockets.

Why is that needed?

**Comment by jameshartig** [comment]
It is needed because the default probe interval and failure counts set by the OS are too extreme and if you have an application that keeps a lot of sockets open (say a server that hosts a lot of clients over socket connections) you'd want to fine-tune the values to be very low.

**Comment by ibc** [comment]
I agree. Depending on OS default values is not (always) good.

**Comment by jameshartig** [comment]
If I make a new pull request pointing at master and add the documentation for count/interval being 0, can it be merged?

**Comment by jameshartig** [comment]
Updated with Windows support for interval, documentation added that @txdv suggested and targeted master.
https://github.com/joyent/libuv/pull/729

**Pull request closed without merging**
