### PR TITLE
win: fix C99/C++ comment

### PR DESCRIPTION
**Pull request by zerhacken**
This commit converts C++ style comment to C style comment

### CODE REVIEW

**Comment by indutny** [comment]
Thanks, LGTM

**Comment by indutny** [comment]
May I ask you to use real name in commit?

**Comment by zerhacken** [comment]
git config --global user.name "Rasmus Pedersen"
git commit --amend --reset-author
git push origin -f dev/win-comment-style

Hope this fixed it @indutny ?

**Comment by indutny** [comment]
Thank you, landed in 616167e!

**Pull request closed without merging**
