### PR TITLE
windows: fix uv__getaddrinfo_translate_error

### PR DESCRIPTION
**Pull request by orangemocha**
The common implementation of uv__getaddrinfo_translate_error
was expecting EAI error codes, but according to MSDN and my testing
GetAddrInfoW returns windows socket error codes.

GetNameInfoW also returns windows socket error codes after calling
WSAGetLastError.

### CODE REVIEW

**Comment by saghul** [comment]
LGTM, thanks Alexis! Will land later tonight.

**Comment by saghul** [comment]
Cheers, Alexis. Landed in :sparkles: https://github.com/joyent/libuv/commit/c87c44fff3f28040159db6ad08134a647e85aacf :sparkles:

**Comment by orangemocha** [comment]
@saghul : thanks! :)

**Comment by txdv** [comment]
The test starts failing on Ubuntu 14.04.

It doesn't recognize the -5 as an error code, which should be EAI_NODATA on my machine, but for some reason it is not defined after moving it to unix/getaddrinfo.c.

https://github.com/lattera/glibc/blob/master/resolv/netdb.h#L629

I also commented on the commit: https://github.com/joyent/libuv/commit/c87c44fff3f28040159db6ad08134a647e85aacf

**Comment by saghul** [comment]
The code is the same as it was before, it just moved AFAIS. Tests pass on Jenkins, when using Ubuntu 14.04: http://jenkins.nodejs.org/job/libuv-master/label=ubuntu-14.04/lastBuild/

I also cannot reproduce locally (Debian Sid). How did you build libuv?

**Comment by txdv** [comment]
Makefile and gyp both fail

**Comment by txdv** [comment]
I just tested in a freshly installed and updated Ubuntu 14.04.1 VM and got the same failure:

```
bentkus@bentkus-VirtualBox:~/Downloads/libuv$ test/run-tests getaddrinfo_fail getaddrinfo_fail
lt-run-tests: src/unix/getaddrinfo.c:81: uv__getaddrinfo_translate_error: Assertion `!"unknown EAI_* error code"' failed.
Aborted (core dumped)
```

**Comment by saghul** [comment]
I'm utterly confused. I just tried on my 14.04.1 laptop (updated right now) and I get no failure :-O Anyway, can you try this? https://github.com/saghul/libuv/commit/a7e8589342cc608edb0a5a3d5d4e5dd11101267c

**Pull request closed without merging**
