### PR TITLE
stream: fix emfile trick

### PR DESCRIPTION
**Pull request by indutny**
No comments.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
Wrong target branch?  I'm willing to believe I broke it in master after the errno rework but in v0.10, uv__accept() still returns either a file descriptor or -1.

**Comment by indutny** [comment]
Yeah, you broke it in master then...

**Comment by indutny** [comment]
mind pulling, anyway? :)

**Comment by indutny** [comment]
@bnoordhuis btw, why are you returning `errno` anyway?

**Pull request closed without merging**
