### PR TITLE
linux: reduce file descriptor count of async pipe

### PR DESCRIPTION
**Pull request by bnoordhuis**
Reopen one of the pipe descriptors as read/write through the procfs.
Allows us to close the original pipe file descriptors, saving a file
descriptor on kernels that don't support eventfd(2).

### CODE REVIEW

**Comment by indutny** [comment]
I thought you had no interest in libuv ;) Will look into it soon.

**Comment by saghul** [comment]
Hi Ben, thanks for the PR! Can you point me to some docs on why/how this (the 'special' fds) works? My google-fu is not helping :-/

**Comment by indutny** [comment]
@saghul because it is the same inode, essentially. Looking good.

**Comment by indutny** [comment]
@saghul if you are ok with it - please land it or at least let me know. ;)

**Comment by indutny** [comment]
Thank you, landed in 86831fe99c625f3a8180c02e628758eb25a0bd3b

**Pull request closed without merging**
