### PR TITLE
build fixes

### PR DESCRIPTION
**Pull request by busterb**
I was testing the latest libuv for a new project and found a few issues in the process. Please consider these fixes for distribution tarballs and newer mingw builds.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
LGTM but can you drop the first commit and reword the others (see `git log` for examples)?  The version number is something we need to address in [the release tool](https://github.com/piscisaureus/libuv-release-tool).  It's on my TODO list, just haven't gotten around to it yet.

**Comment by busterb** [comment]
Updated request, thanks.

**Comment by bnoordhuis** [comment]
Okay, thanks.  Can you sign [the CLA](http://nodejs.org/cla.html)?  I can't land it without.

**Comment by busterb** [comment]
Signed, thanks.

**Comment by bnoordhuis** [comment]
Thanks Brent, landed in c363cd0 and fe3a11e.

**Pull request closed without merging**
