### PR TITLE
build: check if pkg-config is installed

### PR DESCRIPTION
**Pull request by saghul**
My autotools-fu is not very strong,but lets see if the build slaves turn green.

### CODE REVIEW

**Comment by tjfontaine** [comment]
```
checking for pkg-config... no
./configure: line 11647: syntax error near unexpected token `0.20'
./configure: line 11647: `    PKG_PROG_PKG_CONFIG(0.20)'
```

it's checking for pkg-config but not bailing after that

**Comment by tjfontaine** [comment]
I'll leave osx unfixed so we have something to test against

**Comment by saghul** [comment]
Fun, even if I protect it, the mere occurrence of that undefined macro makes autoconf cry.

**Comment by saghul** [comment]
Ok, I managed to avoid the problem. I removed that macro because libuv doesn't itself use pkg-config, it just generates the .pc file, so I don't think we need to check for a specific pkg-config version.

@tjfontaine @indutny thoughts?

**Comment by indutny** [comment]
I'm not really good at autoconf too :) But if it works - I'm ok with it.

**Comment by skaller** [comment]
I also fix that problem by deleting the macro in the configure file. I actually do have pkg-config installed. (but libuv didn't build right anyhow).

**Comment by tjfontaine** [comment]
@saghul I second the notion that there's no need to dep on pkgconfig if you're only generating it

**Comment by saghul** [comment]
Landed it on https://github.com/joyent/libuv/commit/69d2b69647564657625a6118ba911490d0cedcca

**Comment by saghul** [comment]
@skaller what version of autoconf are you using? As I mentioned above the default one in the system won't work because it's too old and contains a bug. Please paste your `./configure` output with current master.

**Comment by indutny** [comment]
@saghul +1

**Comment by saghul** [comment]
I meant to type this on #1030, lets continue there, since the pkg-config thing is fixed now :-)

**Pull request closed without merging**
