### PR TITLE
fsevents: remove kFSEventStreamCreateFlagNoDefer polyfill

### PR DESCRIPTION
**Pull request by ci42**
kFSEventStreamCreateFlagNoDefer already exists in /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/FSEvents.h since OS X 10.5

see #1000

### CODE REVIEW

**Comment by indutny** [comment]
LGTM, but please fix nits mentioned by @Nodejs-Jenkins .

**Comment by ci42** [comment]
@indutny I fixed the commit message. Is the CLA really necessary for a one line change?

**Comment by indutny** [comment]
@ci-innoq I'm afraid - yes.

**Comment by ci42** [comment]
@indutny CLA: done.

**Comment by indutny** [comment]
Thank you! Landed in c438e73

**Pull request closed without merging**
