### PR TITLE
build, windows: fixed x64 configuration issue

### LINKED ISSUE #1072: Building on Windows x64
Having trouble building libuv for Windows x64

Running command `vcbuild.bat release x64` leads to:

``` shell
X:\Documents\GitHub\libuv\ext\libuv\uv.sln.metaproj : error MSB4126: The specified solution configuration "Release|amd64" is invalid.
Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration.
[X:\Documents\GitHub\libuv\ext\libuv\uv.sln]
```

Tried running on CMD and VS CMD
tested with VS 2010 and 2013

### PR DESCRIPTION
**Pull request by schlamar**
This fixes #1072 for me. I guess this is related to changes in gyp.

### CODE REVIEW

**Comment by saghul** [comment]
Thanks @schlamar, landed in https://github.com/joyent/libuv/commit/8010bf9dd2a649bbe1e65b59e7bbd0e6bedd80ba.

**Comment by schlamar** [comment]
@saghul can you backport this to 0.10? pyuv x64 installation on Windows is currently broken.

**Comment by saghul** [comment]
Sure.

**Comment by saghul** [comment]
Backport landed in https://github.com/joyent/libuv/commit/aa2fbb364a2fdd5c90cb9e4ca938787b249ae809

**Pull request closed without merging**
