### PR TITLE
windows: remove redundant code in uv_tcp_write

### PR DESCRIPTION
**Pull request by HungMingWu**

### CODE REVIEW

**Comment by indutny** [comment]
Hello!

Thanks for contributing it, may I ask you to take a look at https://github.com/joyent/libuv/blob/master/CONTRIBUTING.md and fix some minor styling issue, and sign CLA?

**Comment by HungMingWu** [comment]
Hello!
I have signed CLA,, and update the style.
Please check whether I have something miss.

**Comment by indutny** [comment]
@HungMingWu from first look I could say that commit messages do not really apply to the CONTRIBUTING.md ;)

**Comment by indutny** [comment]
Otherwise LGTM!

**Comment by HungMingWu** [comment]
I modify commit message, is it right?

**Comment by indutny** [comment]
A quote from CONTRIBUTING.md:

Writing good commit logs is important.  A commit log should describe what
changed and why.  Follow these guidelines when writing one:
1. The first line should be 50 characters or less and contain a short
   description of the change prefixed with the name of the changed
   subsystem (e.g. "net: add localAddress and localPort to Socket").
2. Keep the second line blank.
3. Wrap all other lines at 72 columns.

A good commit log looks like this:

```
subsystem: explaining the commit in one line

Body of commit message is a few lines of text, explaining things
in more detail, possibly giving some background about the issue
being fixed, etc etc.

The body of the commit message can be several paragraphs, and
please do proper word-wrap and keep columns shorter than about
72 characters or so. That way `git log` will show things
nicely even when it is indented.
```

The header line should be meaningful; it is what other people see when they
run `git shortlog` or `git log --oneline`.

Check the output of `git log --oneline files_that_you_changed` to find out
what subsystem (or subsystems) your changes touch.

**Comment by HungMingWu** [comment]
Thanks for your teaching,  I review my commit log and I think it is right now.
My original thought is edit the pull request title, you remind me.
Thanks for your help.

**Comment by indutny** [comment]
Yay! Looks much better, thanks!

**Comment by indutny** [comment]
Landed in 6d56e6e132717df13c7ed76e6cc3ee53105759be, thank you!

**Pull request closed without merging**
