### PR TITLE
gai errno mapping

### PR DESCRIPTION
**Pull request by mnunberg**
This makes it easier to utilize the UV_ERRNO_MAP

### CODE REVIEW

**Comment by bnoordhuis** [comment]
> This makes it easier to utilize the UV_ERRNO_MAP

This needs some further elaboration. Where/when does it make things easier?

**Comment by mnunberg** [comment]
It's useful when trying to map back uv error codes to their system equivalents.. (there is the `sys_errno_` field which is marked as private...)

See for example https://github.com/mnunberg/couchnode/blob/master/io/common.c#L330 which needs to report the system errno equivalent...

**Comment by bnoordhuis** [comment]
I'm not completely adverse against landing this patch but you should update `src/unix/core.c` and `src/win/getaddrinfo.c` to use the new error codes. Can you sign [the CLA](http://nodejs.org/cla.html) if you haven't yet?

**Comment by bnoordhuis** [comment]
Stale, closing.

**Pull request closed without merging**
