### PR TITLE
unix: fix handling error on UDP socket creation

### PR DESCRIPTION
**Pull request by saghul**
Thanks @ibc for the report and helping with testing :-)

/cc @indutny

### CODE REVIEW

**Comment by saghul** [comment]
Writing a test for this is not easy as we'd need to make uv__socket return an error. It works as it says on the tin :-)

**Comment by indutny** [comment]
You could make it return error by lowering fd limit and triggering ENOENT... But it is rather tricky, indeed.

LGTM, land it! :)

**Comment by saghul** [comment]
Thanks Fedor! :-)

**Comment by ibc** [comment]
I've tested and re-tested with all the possible values for "ulimit -n" (I've open ~65000 UDP sockets right now XD). It just works :)

:cake:

**Pull request merged**
