### PR TITLE
windows: fix buffer leak after failed udp send

### PR DESCRIPTION
**Pull request by piscisaureus**
Ref: #1426

### CODE REVIEW

**Comment by k0dek0mmand0** [comment]
Other than a missing copyright notice at the top of `test-udp-send-unreachable.c` I can't see any problems. I've run it and the test case passes.
I'd personally not remove from the test case the comment about a 'missing' server, but it's clear from the context what's being tested.
I'd also not remove `ASSERT(timer_cb_called == 1);` after `uv_run`.

Thanks for the fix.

**Comment by saghul** [comment]
@k0dek0mmand0 thanks! In the begining I thought we could get away without the timer, but it turns out it's not the case, but I forgot to re-add all the code. Will do.

**Comment by saghul** [comment]
Amended and force pushed.

**Comment by saghul** [comment]
Thanks guys, landed on master!

**Pull request merged**
