### PR TITLE
errno: ENOSPC

### PR DESCRIPTION
**Pull request by tj**

### CODE REVIEW

**Comment by bnoordhuis** [comment]
What's the Windows equivalent of ENOSPC?

/cc @piscisaureus

**Comment by tj** [comment]
no clue :(

**Comment by piscisaureus** [comment]
ERROR_DISK_FULL
Probably map ERROR_EA_TABLE_FULL and maybe ERROR_CANNOT_MAKE too. (figuring that out now)

**Comment by piscisaureus** [comment]
Right. Map these:

``` c
ERROR_DISK_FULL
ERROR_HANDLE_DISK_FULL  /* crt maps to EINVAL */
ERROR_EA_TABLE_FULL     /* crt maps to EINVAL */
ERROR_CANNOT_MAKE       /* cygwin maps to EPERM, and crt maps to EACCES, but afaict this error happens only in a low disk space condition. */
ERROR_END_OF_MEDIA      /* questionable. crt maps to EINVAL */
```

Cygwin maps EAS_DIDNT_FIT to ENOSPC too but that seems wrong. We shouldn't.
EINVAL is apparently the crt way of saying EUNKNOWN.

**Pull request closed without merging**
