### PR TITLE
unix, windows: avoid error in uv_fs_event_stop

### PR DESCRIPTION
**Pull request by saghul**
For consistency with other handle types, if stop is called while the
handle wasn't started yet, it's a no-op.

### CODE REVIEW

**Comment by trevnorris** [comment]
This makes several checks in `test/test-fs-event.c` pointless. Might as well be removed?

**Comment by saghul** [comment]
You mean the checks for the return value? Maybe not right now, but it's possible (in theory) that the function could fail further down and return something other than 0.

**Comment by trevnorris** [comment]
ah, true. I only looked at `unix/kqueue.c`.

**Comment by indutny** [comment]
LGTM

**Comment by saghul** [comment]
Landed!

**Pull request closed without merging**
