### PR TITLE
build: Added install target to the makefile.

### PR DESCRIPTION
**Pull request by navaneeth**
Before this commit, there was no way to install libuv other than
manually copying required files to the path. This commit introduces
an install target which installs the libuv.a, libuv.so and header files
to the install prefix.

```
``
make
make install
``
```

The above will use the default prefix `/usr/local`

```
``
make
make install PREFIX=/usr
``
```

The above will install to `/usr`

### CODE REVIEW

**Comment by bnoordhuis** [comment]
LGTM but can you sign [the CLA](http://nodejs.org/cla.html)? Thanks.

**Comment by navaneeth** [comment]
@bnoordhuis Sure, I did that. Should I send the PDF copy as well?

**Comment by bnoordhuis** [comment]
No need, just signing online is enough. But can you sign it with your full name? Unless Navaneeth is your full name, of course.

**Comment by navaneeth** [comment]
@bnoordhuis Done.

**Comment by bnoordhuis** [comment]
Thanks Navaneeth, landed in 624be53.

**Pull request closed without merging**
