### PR TITLE
test: fix for unit-tests failing on Linux

### PR DESCRIPTION
**Pull request by bajtos**
- fixed process_title() test
- improved logging in test-tty.c to simplify troubleshooting

### CODE REVIEW

**Comment by bajtos** [comment]
According to this [SO answer](http://stackoverflow.com/a/7532195/69868), Jenkins does not allocate terminal when communicating with slaves.

**Comment by bnoordhuis** [comment]
@tjfontaine Is that something that can be addressed in Jenkins? The basic premise of this PR seems okay to me but I would rather not add workarounds for the testing environment.

**Comment by bajtos** [comment]
I dropped the commit replacing tty with pty in test-tty.c. I consider the pull request to be finished, could you please pull it to master (or v0.10) please?

**Comment by bnoordhuis** [comment]
Landed in af6e865 and fe2a315.

**Pull request closed without merging**
