### PR TITLE
fs: fix readdir on empty directory

### PR DESCRIPTION
**Pull request by indutny**
`uv_fd_readdir()` should initialize all fields even if there are no
files. Fix the implementation and fix the test that should have been
covered it.

### CODE REVIEW

**Comment by indutny** [comment]
cc @saghul: this is a blocker for v0.11 release

**Comment by indutny** [comment]
I meant node.js

**Comment by tjfontaine** [comment]
I can note that this does fix the failure on node.js

**Comment by saghul** [comment]
LGTM

**Comment by indutny** [comment]
Landed in 2f54947.

**Pull request merged**
