### PR TITLE
freebsd: use accept4, introduced in version 10

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by saghul** [comment]
Tested it, works, landed. You can blame me later :-)

**Comment by bnoordhuis** [comment]
Belated LGTM FWIW.  You may get a compiler warning on other platforms because `__FreeBSD__` is not defined but only when using very strict settings.

**Comment by saghul** [comment]
On 03/06/2014 06:20 PM, Ben Noordhuis wrote:

> Belated LGTM FWIW. You may get a compiler warning on other platforms
> because |**FreeBSD**| is not defined but only when using very strict
> settings.

Thanks Ben!

## 

Saúl Ibarra Corretgé
bettercallsaghul.com

**Pull request merged**
