### PR TITLE
unix, windows: move includes for EAI constants

### PR DESCRIPTION
**Pull request by saghul**
Lets see if removing those apparently unneded includes make any platform cry...

Wanna review @txdv?

### CODE REVIEW

**Comment by saghul** [comment]
http://jenkins.nodejs.org/job/libuv-pullrequest/648/

**Comment by txdv** [comment]
looks ok, did you compile it on windows?

**Comment by saghul** [comment]
Yep, worked ok.

**Comment by saghul** [comment]
Thanks, Andrius!

**Pull request merged**
