### PR TITLE
Fix #382

### LINKED ISSUE #382: windows: _chsize_s not available on MinGW
After this change: https://github.com/joyent/libuv/commit/d5acfd0c0545acbef5ced2fbcbc6a91c8fc7c025#L3R580 libuv won't compile on MinGW because apparently _chsize_s is not available. Apparently _chsize is limited to 32bits offsets so we can't use that in case the _s version is not available.

### PR DESCRIPTION
**Pull request by Keno**
This should fix #382

### CODE REVIEW

**Comment by piscisaureus** [comment]
Cool. Can you sign the node.js CLA?

http://nodejs.org/cla.html

**Comment by Keno** [comment]
Done

**Comment by piscisaureus** [comment]
Hmm. It doesn't compile, but I'll fix it myself

**Comment by Keno** [comment]
whoops you're right I had a stale commit lying around that I didn't push onto the proper branch

**Comment by piscisaureus** [comment]
Ok, landed with some modifications.

**Pull request closed without merging**
