### PR TITLE
Fix a couple warnings, added some asserts, and compiling with gcc-4.5 and mingw-w64

### PR DESCRIPTION
**Pull request by erickt**

### CODE REVIEW

**Comment by bnoordhuis** [comment]
Merged everything except 484d3ba. @piscisaureus: can you check that commit?

**Comment by piscisaureus** [comment]
@bnoordhuis can't do right now, I have only mingw32 and I'm afraid installing mingw-w64 will break that. Tomorrow I will get mingw-w64 on my office machine and try.

**Comment by nddrylliog** [comment]
@picsisaureus Sorry to disturb, but wouldn't it be a good idea to set up a 32-bit VM and a 64-bit VM ? I know it helps me a lot when developing. You can even install SSH servers on Windows (yeah, they exist) and set up port forwarding in VirtualBox or equivalent so that you can ssh into your virtual machines from anywhere, and automate the builds, it's damn convenient!

**Comment by piscisaureus** [comment]
@erickt
Replacing ws2_32.lib b y -lws2_32 doesn't fly. It breaks the msvc build. Are you sure this is necessary?

**Comment by luislavena** [comment]
If I can chime in, I don't use gyp for MinGW, AFAIK, is not even supported at this time. I use the makefiles directly.

@erickt that is what you tried to solve?

**Comment by erickt** [comment]
I'm okay on punting on the mingw-w64 commit for now. I'll close.

**Pull request closed without merging**
