### PR TITLE
doc,unix: uv_udp_open supports all datagrams

### PR DESCRIPTION
**Pull request by kristrev**
On Unix, uv_udp_open can be used with any socket as long as the socket follows the datagram contract. This means that any datagram-socket, like for example netlink or raw sockets, can be used with libuv. I think this is very useful and expands the possible use cases for libuv, and should be documented.

### CODE REVIEW

**Comment by txdv** [comment]
squash into 1 commit

**Comment by kristrev** [comment]
Thanks for letting me know! Thought I had done it, but apparently not :)

**Comment by kristrev** [comment]
Fixed the messages from Jenkins. Please let me know if there is something else to improve/fix, and if I should create a new pull request with correct commit message.

**Comment by bnoordhuis** [comment]
@kristrev Did you sign the CLA? I can't find you in the list.

Re: commit log, I'd probably prefix it with `include: document etc.`

**Comment by kristrev** [comment]
@bnoordhuis Thanks, I forgot that. I have signed the CLA and updated the commit.

**Comment by bnoordhuis** [comment]
Thanks Kristian, landed in 1e8fe45.

**Pull request closed without merging**
