### PR TITLE
unix, windows: map ERANGE errno

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by saghul** [comment]
getcwd could return this one. /cc @indutny

**Comment by indutny** [comment]
Haha, ok! :)

**Comment by indutny** [comment]
LGTM, needs v0.10 backport as well.

**Comment by saghul** [comment]
On 02/25/2014 10:16 AM, Fedor Indutny wrote:

> LGTM, needs v0.10 backport as well.

Sure.

## 

Saúl Ibarra Corretgé
bettercallsaghul.com

**Comment by saghul** [comment]
On 02/25/2014 10:16 AM, Fedor Indutny wrote:

> LGTM, needs v0.10 backport as well.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/joyent/libuv/pull/1150#issuecomment-35988585.
> 
> Landed the backport.

## 

Saúl Ibarra Corretgé
bettercallsaghul.com

**Pull request merged**
