### PR TITLE
windows: fix environment_creation test

### PR DESCRIPTION
**Pull request by shigeki**
abc945bc04bcd84ecb980988264949013ca35198 fails environment_creation test as

```
`environment_creation` failed: exit code -1073741819
Output from process `environment_creation`: (no output)
```

### CODE REVIEW

**Comment by piscisaureus** [comment]
Thanks, @shigeki. Landed in 09faee4

**Comment by shigeki** [comment]
@piscisaureus Thanks for merge. 
Now, `fs_file_loop` is only one failed test left in my environment.

```
`fs_file_loop` failed: exit code 3
Output from process `fs_file_loop`:
Assertion failed in test\test-fs.c on line 522: uv_last_error(loop).code == UV_ELOOP
```

 Probably it caused by symlink  behavior on Windows but I'm not sure how to fix this.
Does this happen in only my environment or have been left failed intentionally?

**Comment by piscisaureus** [comment]
@shigeki Doesn't happen for me. What windows version are you using?

**Comment by piscisaureus** [comment]
@shigeki Also, when you need to run the test in admin mode, otherwise symlink creation fails.

**Comment by shigeki** [comment]
@piscisaureus That's right. Running test in admin mode make the symlink test success. My environment is WIndows7 SP1 Professional. Thanks.

**Pull request closed without merging**
