### PR TITLE
process: fix bug that mistakenly closes child stdin in some cases

### PR DESCRIPTION
**Pull request by maxtaco**
If a parent process closes 0, and then calls spawn, the following will
happen:
- the first call to socketpair() will return a pair like [0,14]
  in the parent. The kernel allocates fd=0 since it's the lowest
  free file descriptor.
- the child, after fork, in uv__process_child_init,
  calls dup2(use_fd=14,fd=0), which is fine.
- the child then calls close(close_fd=0), which is wrong.

This problem is easily solved by closing the close_fd first, and then
calling dup2 as before.

### CODE REVIEW

**Comment by saghul** [comment]
Can you provide a test?

**Comment by maxtaco** [comment]
Sure, it's taken me a while to get my build env setup.  I assume you don't want to see my node app that was crashing after 1000 lines of debug output.  At the very least I did verify this fixes my node app.  I'll hopefully get something to you soon for test.

**Comment by saghul** [comment]
Great, thank you!

**Comment by maxtaco** [comment]
Ok, a test is provided.  It fails with the master code and passes with my fix.  But, it might be a bug in node, which shouldn't be closing 0 in the first place.

**Comment by indutny** [comment]
@maxtaco what node version are we talking about? I remember fixing one such bug in v0.11, perhaps it wasn't backported to v0.10?

**Comment by indutny** [comment]
cc @tjfontaine

**Comment by maxtaco** [comment]
Correct, my application fails on v0.10 but works on v0.11.  But I didn't drill down too far on why it started working in v0.11.  Our application needs to work on all v0.10's, so we'll put in a workaround.

**Comment by indutny** [comment]
@maxtaco I'm afraid this patch won't make into libuv as it isn't fixing a real problem, which is closing stdio. And the problem was fixed there: https://github.com/joyent/node/commit/fc26fd6b . @tjfontaine could we backport it to v0.10?

**Comment by maxtaco** [comment]
This behavior might come as a surprise for those who use libuv in any application outside of node.  Those applications will see buggy `uv_spawn` behavior after closing stdin.

**Comment by indutny** [comment]
In fact, its not only `uv_spawn()` it may happen in other places too. For me it was happening in a kqueue hack. Anyway, there is no surprise that closing stdio will break things, it will break stuff in many other programs even without libuv.

**Comment by maxtaco** [comment]
For anyone who comes across this PR with similar problems in Node v0.10.x, just do this before spawn, which will open a dummy fd=0 and allow future spawns to work:

``` javascript
if (!process.stdin._handle) {
  fs.fstat(0, function (err) {
    if (err) {
      fs.open(process.execPath, "r", function (err, fd) {});
    }
  });
}
```

**Pull request closed without merging**
