### PR TITLE
unix: don't abort when out of FDs

### LINKED ISSUE #1510: Out of file descriptors should be handled more gracefully
If you call uv_loop_new() and are out of file descriptors there is a chance it will either return NULL or abort().  It should return NULL every time (preferably have some kind of error to handle too) and let the application deal with the problem.

You should be able to reproduce this by calling uv_loop_new() in an endless loop, but there is a chance you could run an application using libuv when you are near the FD limit.

### PR DESCRIPTION
**Pull request by LinuxJedi**
When using uv_loop_new() and the system is low on FDs an abort will be
triggered due to uv_async_init() failing.

To fix this uv_async_init() has been moved up uv__loop_init() so that
allocations are not done before the FD creation and if the FD creation
fails we return -1.  This will gracefully cause uv_loop_new() to fail so
the application can handle it.

Fixes #1510

### CODE REVIEW

**Comment by saghul** [comment]
Thanks! This needs to be applied to the v1.x branch, not v0.10. Then we can think about backporting it.

Also, returning -1 might not be enough, `uv__platform_loop_init` was already called and we'd need to undo what was done there. If `uv_loop_init` fails the user is not expected to call `uv_loop_close`.

**Comment by LinuxJedi** [comment]
ok, no problem, will resubmit in the next 24 hours to the correct branch.

Sorry, I was trying to do this before allocs but must have missed that.  I'll get it to clean up appropriately.

**Comment by saghul** [comment]
Kewl, thanks!

**Comment by LinuxJedi** [comment]
Closing this pull request to open a new one against v1.x branch as requested.

**Pull request closed without merging**
