### PR TITLE
doc: removed duplicate word in uv.h documentation

### PR DESCRIPTION
**Pull request by ghost**
Removed duplicate "other" in:

> Using uv_poll_t for any other other purpose is not recommended

### CODE REVIEW

**Comment by indutny** [comment]
Thank you!

Please take a look at https://github.com/joyent/libuv/blob/master/CONTRIBUTING.md#commit and fix the commit to make it match the requirements.

**Comment by txdv** [comment]
the commit message should be:

doc: remove duplicate word

**Comment by txdv** [comment]
Please use present tense.

It is like a journal. You already have a date so you don't need to specify that it was a in the past.

**Comment by saghul** [comment]
Thanks Tim! Landed in 546fa7d508ba741c106d0161a31e9f8d257a5d56

**Pull request closed without merging**
