### PR TITLE
win: fix uv_thread_self()

### PR DESCRIPTION
**Pull request by orangemocha**
59658a8de7cc05a58327a164fd2ed4b050f8b4f4 changed uv_thread_self()
to return uv_thread_t, but uv_thread_t is a thread's HANDLE while
uv_thread_self() returns the current thread's id.
This means that uv_thread_equal() is also broken, as we are
potentially comparing HANDLES to ids.

Changed uv_thread_self() to return the current thread's creation handle.
Fixed small doc issue.

### CODE REVIEW

**Comment by piscisaureus** [comment]
LGTM, nice work @orangemocha !

**Comment by saghul** [comment]
Thanks Alexis (and Bert for reviewing)! Landed in 6591d00 :sparkles:

**Comment by orangemocha** [comment]
Thanks guys!

**Pull request closed without merging**
