### PR TITLE
include: avoid using C++ 'template' reserved word (fixes #1394)

### LINKED ISSUE #1394: uv_fs_mkdtemp prototype error on osx
UV_EXTERN int uv_fs_mkdtemp(uv_loop_t\* loop, uv_fs_t\* req, const char\* template, 
    uv_fs_cb cb);

using last xcode this prototype give problem, changing "const char\* template" with "const char\* tmp" all work.

### PR DESCRIPTION
**Pull request by ibc**
'template' is a reserved keywork in C++, so including uv.h into a C++ file would fail to compile. This pull request fixes that.

### CODE REVIEW

**Comment by saghul** [comment]
Thanks! Please put the "fixes XXX" in a second line

**Comment by ibc** [comment]
what???

**Comment by saghul** [comment]
Look at this commit https://github.com/joyent/libuv/commit/2cd91f9768361df16505d0c2f67f48a8f1c08c88

**Comment by ibc** [comment]
pfff... done

**Comment by saghul** [comment]
Thanks, landed in master! :+1:

**Comment by ibc** [comment]
:cake:

**Pull request merged**
