### PR TITLE
Add uv_thread_self.

### PR DESCRIPTION
**Pull request by meh**
This adds a function to know the current thread's id.

### CODE REVIEW

**Comment by txdv** [comment]
I don't think this is fits into the libuv API. libuv doesn't handle threads, you can run of course loops in different threads, but you need additional thread functionality and the functionality you are proposing should be included into this additional thread functionality.

**Comment by meh** [comment]
You can create threads and run stuff in threads, you have locking functionalities, how doesn't knowing the current thread fit in there?

**Comment by piscisaureus** [comment]
I don't think it is necessarily a misfit for libuv. The question is whether this API is what people need. @meh What do _you_ need it for?

**Comment by meh** [comment]
OpenSSL multithread support requires a callback to know the current thread id.

**Comment by bnoordhuis** [comment]
I'm not opposed either though I may rename it to `uv_thread_self()` or something.

@meh Can you sign [the CLA](http://nodejs.org/cla.html)?

**Comment by meh** [comment]
> I'm not opposed either though I may rename it to `uv_thread_self()` or something.
> Yeah, I was unsure about the name, if it's easier I can change it when
> you have one and squash the commits.
> 
> @meh Can you sign [the CLA](http://nodejs.org/cla.html)?
> I sure can, but half of the required information is not applicable as
> I don't have a mailing address or telephone.

Is that ok or would it be better if I signoff the commit?

**Comment by bnoordhuis** [comment]
> I sure can, but half of the required information is not applicable as I don't have a mailing address or telephone.

I guess you can put N/A in the fields that don't apply. We'll need your real name though.

**Comment by meh** [comment]
Done. Any idea for a better name?

**Comment by bnoordhuis** [comment]
`uv_thread_self()`? Principle of least disconnect.

**Comment by meh** [comment]
Done.

**Comment by bnoordhuis** [comment]
Thanks, landed in 974c856.

**Pull request closed without merging**
