### PR TITLE
doc: fixed typo in link to nodejs.org

### PR DESCRIPTION
**Pull request by L8D**

### CODE REVIEW

**Comment by piscisaureus** [comment]
@L8D Thanks. Pretty trivial change though :) If you don't mind fixing up your commit (add "doc: " and sign the CLA) then I'll land it. If you don't want to do all that effort I can do it for you.

**Comment by L8D** [comment]
I changed the PR title, but I don’t think I can change the commit message from GitHub, so if you need that changed then you are going to have to do it.

**Comment by piscisaureus** [comment]
You can by amending your commit and force-pushing - http://zite.to/1dIeOgn - but I'll do it for you.

**Comment by L8D** [comment]
yeah, I was referring to amending with the GitHub UI

**Comment by piscisaureus** [comment]
Thanks, landed in 2e58ea8

**Pull request closed without merging**
