### PR TITLE
unix, windows: validate flags on uv_udp|tcp_bind

### LINKED ISSUE #1247: UV_UDP_IPV6ONLY behaves different than UV_TCP_IPV6ONLY
If I bind a IPv4 TCP handler by passing the UV_TCP_IPV6ONLY flag it just works (the IPv6 stuff is ignored as it makes no sense).

If I bind a IPv4 UDP handle by passing the UV_UDP_IPV6ONLY flag then uv_udp_bind() fails with "invalid argument".

### PR DESCRIPTION
**Pull request by saghul**
Fixes #1247.

I'll add some tests.

### CODE REVIEW

**Comment by indutny** [comment]
Needs test ;)

**Comment by saghul** [comment]
Better now? :-)

**Comment by indutny** [comment]
Yes, LGTM :)

**Comment by saghul** [comment]
Thanks Fedor, landed!

**Comment by ibc** [comment]
:cake:

**Pull request merged**
