### PR TITLE
build: Fix configure when PKG_CONFIG is set

### PR DESCRIPTION
**Pull request by thierry-FreeBSD**
If you define the environment variable PKG_CONFIG and assign it to
pkgconf (or pkg-config), configure will say it's OK, but it won't be
used.

### CODE REVIEW

**Comment by saghul** [comment]
@thierry-FreeBSD thanks! could you guide me on validating this? That is, what is the expected outcome after the patch?

**Comment by thierry-FreeBSD** [comment]
After `./autogen.sh', run configure with this command:

PKG_CONFIG=pkgconf ./configure

Without the proposed patch, libuv.pc won't be generated, and the following lines from Makefile.in:

@HAVE_PKG_CONFIG_TRUE@pkgconfigdir = $(libdir)data/pkgconfig
@HAVE_PKG_CONFIG_TRUE@pkgconfig_DATA = @PACKAGE_NAME@.pc

will commented out in Makefile.

With the patch, it will be OK (of course, if pkgconf exists in your $PATH!).

**Comment by saghul** [comment]
Thanks! I'll give it a shot!

**Comment by saghul** [comment]
Thanks @thierry-FreeBSD! I squashed the 2 commits into 1 and landed it in https://github.com/joyent/libuv/commit/b870d914ebbcec2f0124dda6f96e47cdd4abd7d3. FTR, I tested this by setting the PKG_CONFIG env variable pointing to a pkg-config-ish thing written in Python I found in some project (https://gist.github.com/saghul/9287458)

**Pull request closed without merging**
